invokerPackage: "Spy\\MsbcRestClient"
modelPackage: "Model"
apiPackage: "Api"
packagePath: ""
gitUserId: "spysystem"
gitRepoId: "msbc-rest"
httpUserAgent: "OpenAPI-Generator-php"
composerVendorName: "spysystem"
composerProjectName: "msbc-rest"
