<?php
/**
 * CompaniesModelAttributes
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Spy\MsbcRestClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Microsoft Business Center API
 *
 * Generated by: https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Spy\MsbcRestClient\Model;

/**
 * CompaniesModelAttributes Class Doc Comment
 *
 * @category Class
 * @package  Spy\MsbcRestClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CompaniesModelAttributes
{
    public string $strSystemCreatedAt = 'system_created_at';
    public string $strSystemCreatedBy = 'system_created_by';
    public string $strSystemModifiedAt = 'system_modified_at';
    public string $strSystemModifiedBy = 'system_modified_by';
    public string $strId = 'id';
    public string $strSystemVersion = 'system_version';
    public string $strName = 'name';
    public string $strDisplayName = 'display_name';
    public string $strBusinessProfileId = 'business_profile_id';
}

