<?php
/**
 * CreateJournalLineModelFields
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Spy\MsbcRestClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Microsoft Business Center API
 *
 * The Microsoft Business Center API is a RESTful API that provides an interface to the Microsoft Business Center service.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Spy\MsbcRestClient\Model;

/**
 * CreateJournalLineModelFields Class Doc Comment
 *
 * @category Class
 * @package  Spy\MsbcRestClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CreateJournalLineModelFields
{
    public string $strTemplateName = 'templateName';
    public string $strJournalName = 'journalName';
    public string $strDocumentNumber = 'documentNumber';
    public string $strDocumentType = 'documentType';
    public string $strCountryType = 'countryType';
    public string $strAccount = 'account';
    public string $strDescription = 'description';
    public string $strAmount = 'amount';
    public string $strEntryType = 'entryType';
    public string $strPostingDate = 'postingDate';
    public string $strDeliveryAccount = 'deliveryAccount';
    public string $strPostType = 'postType';
    public string $strInvoiceNo = 'invoiceNo';
    public string $strCurrency = 'currency';
    public string $strAmountBaseCurrency = 'amountBaseCurrency';
    public string $strCountyUsTaxAccount = 'countyUSTaxAccount';
    public string $strStateUsTaxAccount = 'stateUSTaxAccount';
    public string $strVatCode = 'vatCode';
    public string $strVatArea = 'vatArea';
    public string $strTaxTitle = 'taxTitle';
    public string $strTaxPercentage = 'taxPercentage';
    public string $strDueDate = 'dueDate';
    public string $strPaymentTerm = 'paymentTerm';
    public string $strCashDiscountDate = 'cashDiscountDate';
    public string $strCustGroup = 'custGroup';
    public string $strSpyDimensions = 'spyDimensions';
}

