<?php
/**
 * SpyCustomerTransResponseModelFields
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Spy\MsbcRestClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Microsoft Business Center API
 *
 * The Microsoft Business Center API is a RESTful API that provides an interface to the Microsoft Business Center service.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Spy\MsbcRestClient\Model;

/**
 * SpyCustomerTransResponseModelFields Class Doc Comment
 *
 * @category Class
 * @package  Spy\MsbcRestClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SpyCustomerTransResponseModelFields
{
    public string $strAtOdataContext = '@odata.context';
    public string $strAtOdataEtag = '@odata.etag';
    public string $strEntryNo = 'Entry_No';
    public string $strPostingDate = 'Posting_Date';
    public string $strDocumentType = 'Document_Type';
    public string $strDocumentNo = 'Document_No';
    public string $strCustomerNo = 'Customer_No';
    public string $strCustomerName = 'Customer_Name';
    public string $strDescription = 'Description';
    public string $strGlobalDimension1Code = 'Global_Dimension_1_Code';
    public string $strGlobalDimension2Code = 'Global_Dimension_2_Code';
    public string $strCustomerPostingGroup = 'Customer_Posting_Group';
    public string $strIcPartnerCode = 'IC_Partner_Code';
    public string $strSalespersonCode = 'Salesperson_Code';
    public string $strCurrencyCode = 'Currency_Code';
    public string $strOriginalAmount = 'Original_Amount';
    public string $strOriginalAmtLcy = 'Original_Amt_LCY';
    public string $strAmount = 'Amount';
    public string $strAmountLcy = 'Amount_LCY';
    public string $strDebitAmount = 'Debit_Amount';
    public string $strDebitAmountLcy = 'Debit_Amount_LCY';
    public string $strCreditAmount = 'Credit_Amount';
    public string $strCreditAmountLcy = 'Credit_Amount_LCY';
    public string $strRemainingAmount = 'Remaining_Amount';
    public string $strRemainingAmtLcy = 'Remaining_Amt_LCY';
    public string $strSalesLcy = 'Sales_LCY';
    public string $strBalAccountType = 'Bal_Account_Type';
    public string $strBalAccountNo = 'Bal_Account_No';
    public string $strDueDate = 'Due_Date';
    public string $strPaymentPrediction = 'Payment_Prediction';
    public string $strPredictionConfidence = 'Prediction_Confidence';
    public string $strPredictionConfidencePercent = 'Prediction_Confidence_Percent';
    public string $strPmtDiscountDate = 'Pmt_Discount_Date';
    public string $strPmtDiscToleranceDate = 'Pmt_Disc_Tolerance_Date';
    public string $strOriginalPmtDiscPossible = 'Original_Pmt_Disc_Possible';
    public string $strRemainingPmtDiscPossible = 'Remaining_Pmt_Disc_Possible';
    public string $strMaxPaymentTolerance = 'Max_Payment_Tolerance';
    public string $strPaymentMethodCode = 'Payment_Method_Code';
    public string $strOpen = 'Open';
    public string $strOnHold = 'On_Hold';
    public string $strUserId = 'User_ID';
    public string $strSourceCode = 'Source_Code';
    public string $strReasonCode = 'Reason_Code';
    public string $strReversed = 'Reversed';
    public string $strReversedByEntryNo = 'Reversed_by_Entry_No';
    public string $strReversedEntryNo = 'Reversed_Entry_No';
    public string $strExportedToPaymentFile = 'Exported_to_Payment_File';
    public string $strMessageToRecipient = 'Message_to_Recipient';
    public string $strDirectDebitMandateId = 'Direct_Debit_Mandate_ID';
    public string $strDimensionSetId = 'Dimension_Set_ID';
    public string $strExternalDocumentNo = 'External_Document_No';
    public string $strRecipientBankAccount = 'RecipientBankAccount';
    public string $strShortcutDimension3Code = 'Shortcut_Dimension_3_Code';
    public string $strShortcutDimension4Code = 'Shortcut_Dimension_4_Code';
    public string $strShortcutDimension5Code = 'Shortcut_Dimension_5_Code';
    public string $strShortcutDimension6Code = 'Shortcut_Dimension_6_Code';
    public string $strShortcutDimension7Code = 'Shortcut_Dimension_7_Code';
    public string $strShortcutDimension8Code = 'Shortcut_Dimension_8_Code';
    public string $strDateFilter = 'Date_Filter';
}

