<?php
/**
 * SpyCustomerModelAttributes
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Spy\MsbcRestClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Microsoft Business Center API
 *
 * The Microsoft Business Center API is a RESTful API that provides an interface to the Microsoft Business Center service.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Spy\MsbcRestClient\Model;

/**
 * SpyCustomerModelAttributes Class Doc Comment
 *
 * @category Class
 * @package  Spy\MsbcRestClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SpyCustomerModelAttributes
{
    public string $strAtOdataEtag = 'at_odata_etag';
    public string $strNo = 'no';
    public string $strName = 'name';
    public string $strSearchName = 'search_name';
    public string $strName2 = 'name_2';
    public string $strAddress = 'address';
    public string $strAddress2 = 'address_2';
    public string $strCity = 'city';
    public string $strContactName = 'contact_name';
    public string $strPhoneNo = 'phone_no';
    public string $strDocumentSendingProfile = 'document_sending_profile';
    public string $strShipToCode = 'ship_to_code';
    public string $strGlobalDimension1Code = 'global_dimension_1_code';
    public string $strGlobalDimension2Code = 'global_dimension_2_code';
    public string $strCreditLimitLcy = 'credit_limit_lcy';
    public string $strCustomerPostingGroup = 'customer_posting_group';
    public string $strCurrencyCode = 'currency_code';
    public string $strCustomerPriceGroup = 'customer_price_group';
    public string $strLanguageCode = 'language_code';
    public string $strPaymentTermsCode = 'payment_terms_code';
    public string $strFinChargeTermsCode = 'fin_charge_terms_code';
    public string $strSalespersonCode = 'salesperson_code';
    public string $strShipmentMethodCode = 'shipment_method_code';
    public string $strShippingAgentCode = 'shipping_agent_code';
    public string $strInvoiceDiscCode = 'invoice_disc_code';
    public string $strCustomerDiscGroup = 'customer_disc_group';
    public string $strCountryRegionCode = 'country_region_code';
    public string $strBlocked = 'blocked';
    public string $strInvoiceCopies = 'invoice_copies';
    public string $strLastStatementNo = 'last_statement_no';
    public string $strPrintStatements = 'print_statements';
    public string $strBillToCustomerNo = 'bill_to_customer_no';
    public string $strPaymentMethodCode = 'payment_method_code';
    public string $strLastDateModified = 'last_date_modified';
    public string $strBalanceLcy = 'balance_lcy';
    public string $strBalanceDueLcy = 'balance_due_lcy';
    public string $strCrMemoAmountsLcy = 'cr_memo_amounts_lcy';
    public string $strApplicationMethod = 'application_method';
    public string $strPricesIncludingVat = 'prices_including_vat';
    public string $strLocationCode = 'location_code';
    public string $strFaxNo = 'fax_no';
    public string $strVatRegistrationNo = 'vat_registration_no';
    public string $strCombineShipments = 'combine_shipments';
    public string $strGenBusPostingGroup = 'gen_bus_posting_group';
    public string $strGln = 'gln';
    public string $strPostCode = 'post_code';
    public string $strCounty = 'county';
    public string $strEoriNumber = 'eori_number';
    public string $strUseGlnInElectronicDocument = 'use_gln_in_electronic_document';
    public string $strEMail = 'e_mail';
    public string $strHomePage = 'home_page';
    public string $strReminderTermsCode = 'reminder_terms_code';
    public string $strTaxAreaCode = 'tax_area_code';
    public string $strTaxLiable = 'tax_liable';
    public string $strVatBusPostingGroup = 'vat_bus_posting_group';
    public string $strReserve = 'reserve';
    public string $strBlockPaymentTolerance = 'block_payment_tolerance';
    public string $strIcPartnerCode = 'ic_partner_code';
    public string $strPrepaymentPercent = 'prepayment_percent';
    public string $strOutstandingInvoicesLcy = 'outstanding_invoices_lcy';
    public string $strPartnerType = 'partner_type';
    public string $strPrivacyBlocked = 'privacy_blocked';
    public string $strDisableSearchByName = 'disable_search_by_name';
    public string $strPreferredBankAccountCode = 'preferred_bank_account_code';
    public string $strCashFlowPaymentTermsCode = 'cash_flow_payment_terms_code';
    public string $strPrimaryContactNo = 'primary_contact_no';
    public string $strMobilePhoneNo = 'mobile_phone_no';
    public string $strResponsibilityCenter = 'responsibility_center';
    public string $strShippingAdvice = 'shipping_advice';
    public string $strShippingTime = 'shipping_time';
    public string $strServiceZoneCode = 'service_zone_code';
    public string $strPriceCalculationMethod = 'price_calculation_method';
    public string $strAllowLineDisc = 'allow_line_disc';
    public string $strBaseCalendarCode = 'base_calendar_code';
    public string $strCopySellToAddrToQteFrom = 'copy_sell_to_addr_to_qte_from';
    public string $strBalanceDue = 'balance_due';
    public string $strShippingAgentServiceCode = 'shipping_agent_service_code';
    public string $strGlobalDimension1Filter = 'global_dimension_1_filter';
    public string $strGlobalDimension2Filter = 'global_dimension_2_filter';
    public string $strCurrencyFilter = 'currency_filter';
    public string $strDateFilter = 'date_filter';
}

