<?php
/**
 * SpyCustomerResponseModelFields
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Spy\MsbcRestClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Microsoft Business Center API
 *
 * The Microsoft Business Center API is a RESTful API that provides an interface to the Microsoft Business Center service.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Spy\MsbcRestClient\Model;

/**
 * SpyCustomerResponseModelFields Class Doc Comment
 *
 * @category Class
 * @package  Spy\MsbcRestClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SpyCustomerResponseModelFields
{
    public string $strAtOdataContext = '@odata.context';
    public string $strAtOdataEtag = '@odata.etag';
    public string $strNo = 'No';
    public string $strName = 'Name';
    public string $strSearchName = 'Search_Name';
    public string $strName2 = 'Name_2';
    public string $strAddress = 'Address';
    public string $strAddress2 = 'Address_2';
    public string $strCity = 'City';
    public string $strContactName = 'ContactName';
    public string $strPhoneNo = 'Phone_No';
    public string $strDocumentSendingProfile = 'Document_Sending_Profile';
    public string $strShipToCode = 'Ship_to_Code';
    public string $strGlobalDimension1Code = 'Global_Dimension_1_Code';
    public string $strGlobalDimension2Code = 'Global_Dimension_2_Code';
    public string $strCreditLimitLcy = 'Credit_Limit_LCY';
    public string $strCustomerPostingGroup = 'Customer_Posting_Group';
    public string $strCurrencyCode = 'Currency_Code';
    public string $strCustomerPriceGroup = 'Customer_Price_Group';
    public string $strLanguageCode = 'Language_Code';
    public string $strPaymentTermsCode = 'Payment_Terms_Code';
    public string $strFinChargeTermsCode = 'Fin_Charge_Terms_Code';
    public string $strSalespersonCode = 'Salesperson_Code';
    public string $strShipmentMethodCode = 'Shipment_Method_Code';
    public string $strShippingAgentCode = 'Shipping_Agent_Code';
    public string $strInvoiceDiscCode = 'Invoice_Disc_Code';
    public string $strCustomerDiscGroup = 'Customer_Disc_Group';
    public string $strCountryRegionCode = 'Country_Region_Code';
    public string $strBlocked = 'Blocked';
    public string $strInvoiceCopies = 'Invoice_Copies';
    public string $strLastStatementNo = 'Last_Statement_No';
    public string $strPrintStatements = 'Print_Statements';
    public string $strBillToCustomerNo = 'Bill_to_Customer_No';
    public string $strPaymentMethodCode = 'Payment_Method_Code';
    public string $strLastDateModified = 'Last_Date_Modified';
    public string $strBalanceLcy = 'Balance_LCY';
    public string $strBalanceDueLcy = 'Balance_Due_LCY';
    public string $strCrMemoAmountsLcy = 'Cr_Memo_Amounts_LCY';
    public string $strApplicationMethod = 'Application_Method';
    public string $strPricesIncludingVat = 'Prices_Including_VAT';
    public string $strLocationCode = 'Location_Code';
    public string $strFaxNo = 'Fax_No';
    public string $strVatRegistrationNo = 'VAT_Registration_No';
    public string $strCombineShipments = 'Combine_Shipments';
    public string $strGenBusPostingGroup = 'Gen_Bus_Posting_Group';
    public string $strGln = 'GLN';
    public string $strPostCode = 'Post_Code';
    public string $strCounty = 'County';
    public string $strEoriNumber = 'EORI_Number';
    public string $strUseGlnInElectronicDocument = 'Use_GLN_in_Electronic_Document';
    public string $strEMail = 'E_Mail';
    public string $strHomePage = 'Home_Page';
    public string $strReminderTermsCode = 'Reminder_Terms_Code';
    public string $strTaxAreaCode = 'Tax_Area_Code';
    public string $strTaxLiable = 'Tax_Liable';
    public string $strVatBusPostingGroup = 'VAT_Bus_Posting_Group';
    public string $strReserve = 'Reserve';
    public string $strBlockPaymentTolerance = 'Block_Payment_Tolerance';
    public string $strIcPartnerCode = 'IC_Partner_Code';
    public string $strPrepaymentPercent = 'Prepayment_Percent';
    public string $strOutstandingInvoicesLcy = 'Outstanding_Invoices_LCY';
    public string $strPartnerType = 'Partner_Type';
    public string $strPrivacyBlocked = 'Privacy_Blocked';
    public string $strDisableSearchByName = 'Disable_Search_by_Name';
    public string $strPreferredBankAccountCode = 'Preferred_Bank_Account_Code';
    public string $strCashFlowPaymentTermsCode = 'Cash_Flow_Payment_Terms_Code';
    public string $strPrimaryContactNo = 'Primary_Contact_No';
    public string $strMobilePhoneNo = 'Mobile_Phone_No';
    public string $strResponsibilityCenter = 'Responsibility_Center';
    public string $strShippingAdvice = 'Shipping_Advice';
    public string $strShippingTime = 'Shipping_Time';
    public string $strServiceZoneCode = 'Service_Zone_Code';
    public string $strPriceCalculationMethod = 'Price_Calculation_Method';
    public string $strAllowLineDisc = 'Allow_Line_Disc';
    public string $strBaseCalendarCode = 'Base_Calendar_Code';
    public string $strCopySellToAddrToQteFrom = 'Copy_Sell_to_Addr_to_Qte_From';
    public string $strBalanceDue = 'Balance_Due';
    public string $strShippingAgentServiceCode = 'Shipping_Agent_Service_Code';
    public string $strGlobalDimension1Filter = 'Global_Dimension_1_Filter';
    public string $strGlobalDimension2Filter = 'Global_Dimension_2_Filter';
    public string $strCurrencyFilter = 'Currency_Filter';
    public string $strDateFilter = 'Date_Filter';
}

