<?php
/**
 * SpyCustomer
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Spy\MsbcRestClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Microsoft Business Center API
 *
 * The Microsoft Business Center API is a RESTful API that provides an interface to the Microsoft Business Center service.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Spy\MsbcRestClient\Model;

use \ArrayAccess;
use \Spy\MsbcRestClient\ObjectSerializer;

/**
 * SpyCustomer Class Doc Comment
 *
 * @category Class
 * @package  Spy\MsbcRestClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SpyCustomer implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * Return an object with the Model Fields
      *
      * @return SpyCustomerModelFields
      */
    public static function GetModelFields(): SpyCustomerModelFields
    {
        return new SpyCustomerModelFields();
    }

    /**
      * Return an object with the Model Attributes
      *
      * @return SpyCustomerModelAttributes
      */
    public static function GetModelAttributes(): SpyCustomerModelAttributes
    {
        return new SpyCustomerModelAttributes();
    }

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SpyCustomer';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'at_odata_etag' => 'string',
        'no' => 'string',
        'name' => 'string',
        'search_name' => 'string',
        'name_2' => 'string',
        'address' => 'string',
        'address_2' => 'string',
        'city' => 'string',
        'contact_name' => 'string',
        'phone_no' => 'string',
        'document_sending_profile' => 'string',
        'ship_to_code' => 'string',
        'global_dimension_1_code' => 'string',
        'global_dimension_2_code' => 'string',
        'credit_limit_lcy' => 'float',
        'customer_posting_group' => 'string',
        'currency_code' => 'string',
        'customer_price_group' => 'string',
        'language_code' => 'string',
        'payment_terms_code' => 'string',
        'fin_charge_terms_code' => 'string',
        'salesperson_code' => 'string',
        'shipment_method_code' => 'string',
        'shipping_agent_code' => 'string',
        'invoice_disc_code' => 'string',
        'customer_disc_group' => 'string',
        'country_region_code' => 'string',
        'blocked' => 'string',
        'invoice_copies' => 'int',
        'last_statement_no' => 'int',
        'print_statements' => 'bool',
        'bill_to_customer_no' => 'string',
        'payment_method_code' => 'string',
        'last_date_modified' => 'string',
        'balance_lcy' => 'float',
        'balance_due_lcy' => 'float',
        'cr_memo_amounts_lcy' => 'float',
        'application_method' => 'string',
        'prices_including_vat' => 'bool',
        'location_code' => 'string',
        'fax_no' => 'string',
        'vat_registration_no' => 'string',
        'combine_shipments' => 'bool',
        'gen_bus_posting_group' => 'string',
        'gln' => 'string',
        'post_code' => 'string',
        'county' => 'string',
        'eori_number' => 'string',
        'use_gln_in_electronic_document' => 'bool',
        'e_mail' => 'string',
        'home_page' => 'string',
        'reminder_terms_code' => 'string',
        'tax_area_code' => 'string',
        'tax_liable' => 'bool',
        'vat_bus_posting_group' => 'string',
        'reserve' => 'string',
        'block_payment_tolerance' => 'bool',
        'ic_partner_code' => 'string',
        'prepayment_percent' => 'float',
        'outstanding_invoices_lcy' => 'float',
        'partner_type' => 'string',
        'privacy_blocked' => 'bool',
        'disable_search_by_name' => 'bool',
        'preferred_bank_account_code' => 'string',
        'cash_flow_payment_terms_code' => 'string',
        'primary_contact_no' => 'string',
        'mobile_phone_no' => 'string',
        'responsibility_center' => 'string',
        'shipping_advice' => 'string',
        'shipping_time' => 'string',
        'service_zone_code' => 'string',
        'price_calculation_method' => 'string',
        'allow_line_disc' => 'bool',
        'base_calendar_code' => 'string',
        'copy_sell_to_addr_to_qte_from' => 'string',
        'balance_due' => 'float',
        'shipping_agent_service_code' => 'string',
        'global_dimension_1_filter' => 'string',
        'global_dimension_2_filter' => 'string',
        'currency_filter' => 'string',
        'date_filter' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'at_odata_etag' => null,
        'no' => null,
        'name' => null,
        'search_name' => null,
        'name_2' => null,
        'address' => null,
        'address_2' => null,
        'city' => null,
        'contact_name' => null,
        'phone_no' => null,
        'document_sending_profile' => null,
        'ship_to_code' => null,
        'global_dimension_1_code' => null,
        'global_dimension_2_code' => null,
        'credit_limit_lcy' => null,
        'customer_posting_group' => null,
        'currency_code' => null,
        'customer_price_group' => null,
        'language_code' => null,
        'payment_terms_code' => null,
        'fin_charge_terms_code' => null,
        'salesperson_code' => null,
        'shipment_method_code' => null,
        'shipping_agent_code' => null,
        'invoice_disc_code' => null,
        'customer_disc_group' => null,
        'country_region_code' => null,
        'blocked' => null,
        'invoice_copies' => null,
        'last_statement_no' => null,
        'print_statements' => null,
        'bill_to_customer_no' => null,
        'payment_method_code' => null,
        'last_date_modified' => null,
        'balance_lcy' => null,
        'balance_due_lcy' => null,
        'cr_memo_amounts_lcy' => null,
        'application_method' => null,
        'prices_including_vat' => null,
        'location_code' => null,
        'fax_no' => null,
        'vat_registration_no' => null,
        'combine_shipments' => null,
        'gen_bus_posting_group' => null,
        'gln' => null,
        'post_code' => null,
        'county' => null,
        'eori_number' => null,
        'use_gln_in_electronic_document' => null,
        'e_mail' => null,
        'home_page' => null,
        'reminder_terms_code' => null,
        'tax_area_code' => null,
        'tax_liable' => null,
        'vat_bus_posting_group' => null,
        'reserve' => null,
        'block_payment_tolerance' => null,
        'ic_partner_code' => null,
        'prepayment_percent' => null,
        'outstanding_invoices_lcy' => null,
        'partner_type' => null,
        'privacy_blocked' => null,
        'disable_search_by_name' => null,
        'preferred_bank_account_code' => null,
        'cash_flow_payment_terms_code' => null,
        'primary_contact_no' => null,
        'mobile_phone_no' => null,
        'responsibility_center' => null,
        'shipping_advice' => null,
        'shipping_time' => null,
        'service_zone_code' => null,
        'price_calculation_method' => null,
        'allow_line_disc' => null,
        'base_calendar_code' => null,
        'copy_sell_to_addr_to_qte_from' => null,
        'balance_due' => null,
        'shipping_agent_service_code' => null,
        'global_dimension_1_filter' => null,
        'global_dimension_2_filter' => null,
        'currency_filter' => null,
        'date_filter' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'at_odata_etag' => false,
		'no' => false,
		'name' => false,
		'search_name' => false,
		'name_2' => false,
		'address' => false,
		'address_2' => false,
		'city' => false,
		'contact_name' => false,
		'phone_no' => false,
		'document_sending_profile' => false,
		'ship_to_code' => false,
		'global_dimension_1_code' => false,
		'global_dimension_2_code' => false,
		'credit_limit_lcy' => false,
		'customer_posting_group' => false,
		'currency_code' => false,
		'customer_price_group' => false,
		'language_code' => false,
		'payment_terms_code' => false,
		'fin_charge_terms_code' => false,
		'salesperson_code' => false,
		'shipment_method_code' => false,
		'shipping_agent_code' => false,
		'invoice_disc_code' => false,
		'customer_disc_group' => false,
		'country_region_code' => false,
		'blocked' => false,
		'invoice_copies' => false,
		'last_statement_no' => false,
		'print_statements' => false,
		'bill_to_customer_no' => false,
		'payment_method_code' => false,
		'last_date_modified' => false,
		'balance_lcy' => false,
		'balance_due_lcy' => false,
		'cr_memo_amounts_lcy' => false,
		'application_method' => false,
		'prices_including_vat' => false,
		'location_code' => false,
		'fax_no' => false,
		'vat_registration_no' => false,
		'combine_shipments' => false,
		'gen_bus_posting_group' => false,
		'gln' => false,
		'post_code' => false,
		'county' => false,
		'eori_number' => false,
		'use_gln_in_electronic_document' => false,
		'e_mail' => false,
		'home_page' => false,
		'reminder_terms_code' => false,
		'tax_area_code' => false,
		'tax_liable' => false,
		'vat_bus_posting_group' => false,
		'reserve' => false,
		'block_payment_tolerance' => false,
		'ic_partner_code' => false,
		'prepayment_percent' => false,
		'outstanding_invoices_lcy' => false,
		'partner_type' => false,
		'privacy_blocked' => false,
		'disable_search_by_name' => false,
		'preferred_bank_account_code' => false,
		'cash_flow_payment_terms_code' => false,
		'primary_contact_no' => false,
		'mobile_phone_no' => false,
		'responsibility_center' => false,
		'shipping_advice' => false,
		'shipping_time' => false,
		'service_zone_code' => false,
		'price_calculation_method' => false,
		'allow_line_disc' => false,
		'base_calendar_code' => false,
		'copy_sell_to_addr_to_qte_from' => false,
		'balance_due' => false,
		'shipping_agent_service_code' => false,
		'global_dimension_1_filter' => false,
		'global_dimension_2_filter' => false,
		'currency_filter' => false,
		'date_filter' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'at_odata_etag' => '@odata.etag',
        'no' => 'No',
        'name' => 'Name',
        'search_name' => 'Search_Name',
        'name_2' => 'Name_2',
        'address' => 'Address',
        'address_2' => 'Address_2',
        'city' => 'City',
        'contact_name' => 'ContactName',
        'phone_no' => 'Phone_No',
        'document_sending_profile' => 'Document_Sending_Profile',
        'ship_to_code' => 'Ship_to_Code',
        'global_dimension_1_code' => 'Global_Dimension_1_Code',
        'global_dimension_2_code' => 'Global_Dimension_2_Code',
        'credit_limit_lcy' => 'Credit_Limit_LCY',
        'customer_posting_group' => 'Customer_Posting_Group',
        'currency_code' => 'Currency_Code',
        'customer_price_group' => 'Customer_Price_Group',
        'language_code' => 'Language_Code',
        'payment_terms_code' => 'Payment_Terms_Code',
        'fin_charge_terms_code' => 'Fin_Charge_Terms_Code',
        'salesperson_code' => 'Salesperson_Code',
        'shipment_method_code' => 'Shipment_Method_Code',
        'shipping_agent_code' => 'Shipping_Agent_Code',
        'invoice_disc_code' => 'Invoice_Disc_Code',
        'customer_disc_group' => 'Customer_Disc_Group',
        'country_region_code' => 'Country_Region_Code',
        'blocked' => 'Blocked',
        'invoice_copies' => 'Invoice_Copies',
        'last_statement_no' => 'Last_Statement_No',
        'print_statements' => 'Print_Statements',
        'bill_to_customer_no' => 'Bill_to_Customer_No',
        'payment_method_code' => 'Payment_Method_Code',
        'last_date_modified' => 'Last_Date_Modified',
        'balance_lcy' => 'Balance_LCY',
        'balance_due_lcy' => 'Balance_Due_LCY',
        'cr_memo_amounts_lcy' => 'Cr_Memo_Amounts_LCY',
        'application_method' => 'Application_Method',
        'prices_including_vat' => 'Prices_Including_VAT',
        'location_code' => 'Location_Code',
        'fax_no' => 'Fax_No',
        'vat_registration_no' => 'VAT_Registration_No',
        'combine_shipments' => 'Combine_Shipments',
        'gen_bus_posting_group' => 'Gen_Bus_Posting_Group',
        'gln' => 'GLN',
        'post_code' => 'Post_Code',
        'county' => 'County',
        'eori_number' => 'EORI_Number',
        'use_gln_in_electronic_document' => 'Use_GLN_in_Electronic_Document',
        'e_mail' => 'E_Mail',
        'home_page' => 'Home_Page',
        'reminder_terms_code' => 'Reminder_Terms_Code',
        'tax_area_code' => 'Tax_Area_Code',
        'tax_liable' => 'Tax_Liable',
        'vat_bus_posting_group' => 'VAT_Bus_Posting_Group',
        'reserve' => 'Reserve',
        'block_payment_tolerance' => 'Block_Payment_Tolerance',
        'ic_partner_code' => 'IC_Partner_Code',
        'prepayment_percent' => 'Prepayment_Percent',
        'outstanding_invoices_lcy' => 'Outstanding_Invoices_LCY',
        'partner_type' => 'Partner_Type',
        'privacy_blocked' => 'Privacy_Blocked',
        'disable_search_by_name' => 'Disable_Search_by_Name',
        'preferred_bank_account_code' => 'Preferred_Bank_Account_Code',
        'cash_flow_payment_terms_code' => 'Cash_Flow_Payment_Terms_Code',
        'primary_contact_no' => 'Primary_Contact_No',
        'mobile_phone_no' => 'Mobile_Phone_No',
        'responsibility_center' => 'Responsibility_Center',
        'shipping_advice' => 'Shipping_Advice',
        'shipping_time' => 'Shipping_Time',
        'service_zone_code' => 'Service_Zone_Code',
        'price_calculation_method' => 'Price_Calculation_Method',
        'allow_line_disc' => 'Allow_Line_Disc',
        'base_calendar_code' => 'Base_Calendar_Code',
        'copy_sell_to_addr_to_qte_from' => 'Copy_Sell_to_Addr_to_Qte_From',
        'balance_due' => 'Balance_Due',
        'shipping_agent_service_code' => 'Shipping_Agent_Service_Code',
        'global_dimension_1_filter' => 'Global_Dimension_1_Filter',
        'global_dimension_2_filter' => 'Global_Dimension_2_Filter',
        'currency_filter' => 'Currency_Filter',
        'date_filter' => 'Date_Filter'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'at_odata_etag' => 'setAtOdataEtag',
        'no' => 'setNo',
        'name' => 'setName',
        'search_name' => 'setSearchName',
        'name_2' => 'setName2',
        'address' => 'setAddress',
        'address_2' => 'setAddress2',
        'city' => 'setCity',
        'contact_name' => 'setContactName',
        'phone_no' => 'setPhoneNo',
        'document_sending_profile' => 'setDocumentSendingProfile',
        'ship_to_code' => 'setShipToCode',
        'global_dimension_1_code' => 'setGlobalDimension1Code',
        'global_dimension_2_code' => 'setGlobalDimension2Code',
        'credit_limit_lcy' => 'setCreditLimitLcy',
        'customer_posting_group' => 'setCustomerPostingGroup',
        'currency_code' => 'setCurrencyCode',
        'customer_price_group' => 'setCustomerPriceGroup',
        'language_code' => 'setLanguageCode',
        'payment_terms_code' => 'setPaymentTermsCode',
        'fin_charge_terms_code' => 'setFinChargeTermsCode',
        'salesperson_code' => 'setSalespersonCode',
        'shipment_method_code' => 'setShipmentMethodCode',
        'shipping_agent_code' => 'setShippingAgentCode',
        'invoice_disc_code' => 'setInvoiceDiscCode',
        'customer_disc_group' => 'setCustomerDiscGroup',
        'country_region_code' => 'setCountryRegionCode',
        'blocked' => 'setBlocked',
        'invoice_copies' => 'setInvoiceCopies',
        'last_statement_no' => 'setLastStatementNo',
        'print_statements' => 'setPrintStatements',
        'bill_to_customer_no' => 'setBillToCustomerNo',
        'payment_method_code' => 'setPaymentMethodCode',
        'last_date_modified' => 'setLastDateModified',
        'balance_lcy' => 'setBalanceLcy',
        'balance_due_lcy' => 'setBalanceDueLcy',
        'cr_memo_amounts_lcy' => 'setCrMemoAmountsLcy',
        'application_method' => 'setApplicationMethod',
        'prices_including_vat' => 'setPricesIncludingVat',
        'location_code' => 'setLocationCode',
        'fax_no' => 'setFaxNo',
        'vat_registration_no' => 'setVatRegistrationNo',
        'combine_shipments' => 'setCombineShipments',
        'gen_bus_posting_group' => 'setGenBusPostingGroup',
        'gln' => 'setGln',
        'post_code' => 'setPostCode',
        'county' => 'setCounty',
        'eori_number' => 'setEoriNumber',
        'use_gln_in_electronic_document' => 'setUseGlnInElectronicDocument',
        'e_mail' => 'setEMail',
        'home_page' => 'setHomePage',
        'reminder_terms_code' => 'setReminderTermsCode',
        'tax_area_code' => 'setTaxAreaCode',
        'tax_liable' => 'setTaxLiable',
        'vat_bus_posting_group' => 'setVatBusPostingGroup',
        'reserve' => 'setReserve',
        'block_payment_tolerance' => 'setBlockPaymentTolerance',
        'ic_partner_code' => 'setIcPartnerCode',
        'prepayment_percent' => 'setPrepaymentPercent',
        'outstanding_invoices_lcy' => 'setOutstandingInvoicesLcy',
        'partner_type' => 'setPartnerType',
        'privacy_blocked' => 'setPrivacyBlocked',
        'disable_search_by_name' => 'setDisableSearchByName',
        'preferred_bank_account_code' => 'setPreferredBankAccountCode',
        'cash_flow_payment_terms_code' => 'setCashFlowPaymentTermsCode',
        'primary_contact_no' => 'setPrimaryContactNo',
        'mobile_phone_no' => 'setMobilePhoneNo',
        'responsibility_center' => 'setResponsibilityCenter',
        'shipping_advice' => 'setShippingAdvice',
        'shipping_time' => 'setShippingTime',
        'service_zone_code' => 'setServiceZoneCode',
        'price_calculation_method' => 'setPriceCalculationMethod',
        'allow_line_disc' => 'setAllowLineDisc',
        'base_calendar_code' => 'setBaseCalendarCode',
        'copy_sell_to_addr_to_qte_from' => 'setCopySellToAddrToQteFrom',
        'balance_due' => 'setBalanceDue',
        'shipping_agent_service_code' => 'setShippingAgentServiceCode',
        'global_dimension_1_filter' => 'setGlobalDimension1Filter',
        'global_dimension_2_filter' => 'setGlobalDimension2Filter',
        'currency_filter' => 'setCurrencyFilter',
        'date_filter' => 'setDateFilter'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'at_odata_etag' => 'getAtOdataEtag',
        'no' => 'getNo',
        'name' => 'getName',
        'search_name' => 'getSearchName',
        'name_2' => 'getName2',
        'address' => 'getAddress',
        'address_2' => 'getAddress2',
        'city' => 'getCity',
        'contact_name' => 'getContactName',
        'phone_no' => 'getPhoneNo',
        'document_sending_profile' => 'getDocumentSendingProfile',
        'ship_to_code' => 'getShipToCode',
        'global_dimension_1_code' => 'getGlobalDimension1Code',
        'global_dimension_2_code' => 'getGlobalDimension2Code',
        'credit_limit_lcy' => 'getCreditLimitLcy',
        'customer_posting_group' => 'getCustomerPostingGroup',
        'currency_code' => 'getCurrencyCode',
        'customer_price_group' => 'getCustomerPriceGroup',
        'language_code' => 'getLanguageCode',
        'payment_terms_code' => 'getPaymentTermsCode',
        'fin_charge_terms_code' => 'getFinChargeTermsCode',
        'salesperson_code' => 'getSalespersonCode',
        'shipment_method_code' => 'getShipmentMethodCode',
        'shipping_agent_code' => 'getShippingAgentCode',
        'invoice_disc_code' => 'getInvoiceDiscCode',
        'customer_disc_group' => 'getCustomerDiscGroup',
        'country_region_code' => 'getCountryRegionCode',
        'blocked' => 'getBlocked',
        'invoice_copies' => 'getInvoiceCopies',
        'last_statement_no' => 'getLastStatementNo',
        'print_statements' => 'getPrintStatements',
        'bill_to_customer_no' => 'getBillToCustomerNo',
        'payment_method_code' => 'getPaymentMethodCode',
        'last_date_modified' => 'getLastDateModified',
        'balance_lcy' => 'getBalanceLcy',
        'balance_due_lcy' => 'getBalanceDueLcy',
        'cr_memo_amounts_lcy' => 'getCrMemoAmountsLcy',
        'application_method' => 'getApplicationMethod',
        'prices_including_vat' => 'getPricesIncludingVat',
        'location_code' => 'getLocationCode',
        'fax_no' => 'getFaxNo',
        'vat_registration_no' => 'getVatRegistrationNo',
        'combine_shipments' => 'getCombineShipments',
        'gen_bus_posting_group' => 'getGenBusPostingGroup',
        'gln' => 'getGln',
        'post_code' => 'getPostCode',
        'county' => 'getCounty',
        'eori_number' => 'getEoriNumber',
        'use_gln_in_electronic_document' => 'getUseGlnInElectronicDocument',
        'e_mail' => 'getEMail',
        'home_page' => 'getHomePage',
        'reminder_terms_code' => 'getReminderTermsCode',
        'tax_area_code' => 'getTaxAreaCode',
        'tax_liable' => 'getTaxLiable',
        'vat_bus_posting_group' => 'getVatBusPostingGroup',
        'reserve' => 'getReserve',
        'block_payment_tolerance' => 'getBlockPaymentTolerance',
        'ic_partner_code' => 'getIcPartnerCode',
        'prepayment_percent' => 'getPrepaymentPercent',
        'outstanding_invoices_lcy' => 'getOutstandingInvoicesLcy',
        'partner_type' => 'getPartnerType',
        'privacy_blocked' => 'getPrivacyBlocked',
        'disable_search_by_name' => 'getDisableSearchByName',
        'preferred_bank_account_code' => 'getPreferredBankAccountCode',
        'cash_flow_payment_terms_code' => 'getCashFlowPaymentTermsCode',
        'primary_contact_no' => 'getPrimaryContactNo',
        'mobile_phone_no' => 'getMobilePhoneNo',
        'responsibility_center' => 'getResponsibilityCenter',
        'shipping_advice' => 'getShippingAdvice',
        'shipping_time' => 'getShippingTime',
        'service_zone_code' => 'getServiceZoneCode',
        'price_calculation_method' => 'getPriceCalculationMethod',
        'allow_line_disc' => 'getAllowLineDisc',
        'base_calendar_code' => 'getBaseCalendarCode',
        'copy_sell_to_addr_to_qte_from' => 'getCopySellToAddrToQteFrom',
        'balance_due' => 'getBalanceDue',
        'shipping_agent_service_code' => 'getShippingAgentServiceCode',
        'global_dimension_1_filter' => 'getGlobalDimension1Filter',
        'global_dimension_2_filter' => 'getGlobalDimension2Filter',
        'currency_filter' => 'getCurrencyFilter',
        'date_filter' => 'getDateFilter'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const BLOCKED_SPACE_1 = ' ';
    public const BLOCKED_SHIP = 'Ship';
    public const BLOCKED_INVOICE = 'Invoice';
    public const BLOCKED_ALL = 'All';
    public const APPLICATION_METHOD_MANUAL = 'Manual';
    public const APPLICATION_METHOD_APPLY_TO_OLDEST = 'Apply to Oldest';
    public const RESERVE_NEVER = 'Never';
    public const RESERVE_OPTIONAL = 'Optional';
    public const RESERVE_ALWAYS = 'Always';
    public const PARTNER_TYPE_SPACE_1 = ' ';
    public const PARTNER_TYPE_COMPANY = 'Company';
    public const PARTNER_TYPE_PERSON = 'Person';
    public const SHIPPING_ADVICE_PARTIAL = 'Partial';
    public const SHIPPING_ADVICE_COMPLETE = 'Complete';
    public const PRICE_CALCULATION_METHOD_SPACE_1 = ' ';
    public const PRICE_CALCULATION_METHOD_LOWEST_PRICE = 'Lowest Price';
    public const COPY_SELL_TO_ADDR_TO_QTE_FROM_COMPANY = 'Company';
    public const COPY_SELL_TO_ADDR_TO_QTE_FROM_PERSON = 'Person';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getBlockedAllowableValues()
    {
        return [
            self::BLOCKED_SPACE_1,
            self::BLOCKED_SHIP,
            self::BLOCKED_INVOICE,
            self::BLOCKED_ALL,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getApplicationMethodAllowableValues()
    {
        return [
            self::APPLICATION_METHOD_MANUAL,
            self::APPLICATION_METHOD_APPLY_TO_OLDEST,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getReserveAllowableValues()
    {
        return [
            self::RESERVE_NEVER,
            self::RESERVE_OPTIONAL,
            self::RESERVE_ALWAYS,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPartnerTypeAllowableValues()
    {
        return [
            self::PARTNER_TYPE_SPACE_1,
            self::PARTNER_TYPE_COMPANY,
            self::PARTNER_TYPE_PERSON,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getShippingAdviceAllowableValues()
    {
        return [
            self::SHIPPING_ADVICE_PARTIAL,
            self::SHIPPING_ADVICE_COMPLETE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPriceCalculationMethodAllowableValues()
    {
        return [
            self::PRICE_CALCULATION_METHOD_SPACE_1,
            self::PRICE_CALCULATION_METHOD_LOWEST_PRICE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCopySellToAddrToQteFromAllowableValues()
    {
        return [
            self::COPY_SELL_TO_ADDR_TO_QTE_FROM_COMPANY,
            self::COPY_SELL_TO_ADDR_TO_QTE_FROM_PERSON,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('at_odata_etag', $data ?? [], null);
        $this->setIfExists('no', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('search_name', $data ?? [], null);
        $this->setIfExists('name_2', $data ?? [], null);
        $this->setIfExists('address', $data ?? [], null);
        $this->setIfExists('address_2', $data ?? [], null);
        $this->setIfExists('city', $data ?? [], null);
        $this->setIfExists('contact_name', $data ?? [], null);
        $this->setIfExists('phone_no', $data ?? [], null);
        $this->setIfExists('document_sending_profile', $data ?? [], null);
        $this->setIfExists('ship_to_code', $data ?? [], null);
        $this->setIfExists('global_dimension_1_code', $data ?? [], null);
        $this->setIfExists('global_dimension_2_code', $data ?? [], null);
        $this->setIfExists('credit_limit_lcy', $data ?? [], null);
        $this->setIfExists('customer_posting_group', $data ?? [], null);
        $this->setIfExists('currency_code', $data ?? [], null);
        $this->setIfExists('customer_price_group', $data ?? [], null);
        $this->setIfExists('language_code', $data ?? [], null);
        $this->setIfExists('payment_terms_code', $data ?? [], null);
        $this->setIfExists('fin_charge_terms_code', $data ?? [], null);
        $this->setIfExists('salesperson_code', $data ?? [], null);
        $this->setIfExists('shipment_method_code', $data ?? [], null);
        $this->setIfExists('shipping_agent_code', $data ?? [], null);
        $this->setIfExists('invoice_disc_code', $data ?? [], null);
        $this->setIfExists('customer_disc_group', $data ?? [], null);
        $this->setIfExists('country_region_code', $data ?? [], null);
        $this->setIfExists('blocked', $data ?? [], null);
        $this->setIfExists('invoice_copies', $data ?? [], null);
        $this->setIfExists('last_statement_no', $data ?? [], null);
        $this->setIfExists('print_statements', $data ?? [], null);
        $this->setIfExists('bill_to_customer_no', $data ?? [], null);
        $this->setIfExists('payment_method_code', $data ?? [], null);
        $this->setIfExists('last_date_modified', $data ?? [], null);
        $this->setIfExists('balance_lcy', $data ?? [], null);
        $this->setIfExists('balance_due_lcy', $data ?? [], null);
        $this->setIfExists('cr_memo_amounts_lcy', $data ?? [], null);
        $this->setIfExists('application_method', $data ?? [], null);
        $this->setIfExists('prices_including_vat', $data ?? [], null);
        $this->setIfExists('location_code', $data ?? [], null);
        $this->setIfExists('fax_no', $data ?? [], null);
        $this->setIfExists('vat_registration_no', $data ?? [], null);
        $this->setIfExists('combine_shipments', $data ?? [], null);
        $this->setIfExists('gen_bus_posting_group', $data ?? [], null);
        $this->setIfExists('gln', $data ?? [], null);
        $this->setIfExists('post_code', $data ?? [], null);
        $this->setIfExists('county', $data ?? [], null);
        $this->setIfExists('eori_number', $data ?? [], null);
        $this->setIfExists('use_gln_in_electronic_document', $data ?? [], null);
        $this->setIfExists('e_mail', $data ?? [], null);
        $this->setIfExists('home_page', $data ?? [], null);
        $this->setIfExists('reminder_terms_code', $data ?? [], null);
        $this->setIfExists('tax_area_code', $data ?? [], null);
        $this->setIfExists('tax_liable', $data ?? [], null);
        $this->setIfExists('vat_bus_posting_group', $data ?? [], null);
        $this->setIfExists('reserve', $data ?? [], null);
        $this->setIfExists('block_payment_tolerance', $data ?? [], null);
        $this->setIfExists('ic_partner_code', $data ?? [], null);
        $this->setIfExists('prepayment_percent', $data ?? [], null);
        $this->setIfExists('outstanding_invoices_lcy', $data ?? [], null);
        $this->setIfExists('partner_type', $data ?? [], null);
        $this->setIfExists('privacy_blocked', $data ?? [], null);
        $this->setIfExists('disable_search_by_name', $data ?? [], null);
        $this->setIfExists('preferred_bank_account_code', $data ?? [], null);
        $this->setIfExists('cash_flow_payment_terms_code', $data ?? [], null);
        $this->setIfExists('primary_contact_no', $data ?? [], null);
        $this->setIfExists('mobile_phone_no', $data ?? [], null);
        $this->setIfExists('responsibility_center', $data ?? [], null);
        $this->setIfExists('shipping_advice', $data ?? [], null);
        $this->setIfExists('shipping_time', $data ?? [], null);
        $this->setIfExists('service_zone_code', $data ?? [], null);
        $this->setIfExists('price_calculation_method', $data ?? [], null);
        $this->setIfExists('allow_line_disc', $data ?? [], null);
        $this->setIfExists('base_calendar_code', $data ?? [], null);
        $this->setIfExists('copy_sell_to_addr_to_qte_from', $data ?? [], null);
        $this->setIfExists('balance_due', $data ?? [], null);
        $this->setIfExists('shipping_agent_service_code', $data ?? [], null);
        $this->setIfExists('global_dimension_1_filter', $data ?? [], null);
        $this->setIfExists('global_dimension_2_filter', $data ?? [], null);
        $this->setIfExists('currency_filter', $data ?? [], null);
        $this->setIfExists('date_filter', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getBlockedAllowableValues();
        if (!is_null($this->container['blocked']) && !in_array($this->container['blocked'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'blocked', must be one of '%s'",
                $this->container['blocked'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getApplicationMethodAllowableValues();
        if (!is_null($this->container['application_method']) && !in_array($this->container['application_method'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'application_method', must be one of '%s'",
                $this->container['application_method'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getReserveAllowableValues();
        if (!is_null($this->container['reserve']) && !in_array($this->container['reserve'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'reserve', must be one of '%s'",
                $this->container['reserve'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getPartnerTypeAllowableValues();
        if (!is_null($this->container['partner_type']) && !in_array($this->container['partner_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'partner_type', must be one of '%s'",
                $this->container['partner_type'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getShippingAdviceAllowableValues();
        if (!is_null($this->container['shipping_advice']) && !in_array($this->container['shipping_advice'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'shipping_advice', must be one of '%s'",
                $this->container['shipping_advice'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getPriceCalculationMethodAllowableValues();
        if (!is_null($this->container['price_calculation_method']) && !in_array($this->container['price_calculation_method'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'price_calculation_method', must be one of '%s'",
                $this->container['price_calculation_method'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getCopySellToAddrToQteFromAllowableValues();
        if (!is_null($this->container['copy_sell_to_addr_to_qte_from']) && !in_array($this->container['copy_sell_to_addr_to_qte_from'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'copy_sell_to_addr_to_qte_from', must be one of '%s'",
                $this->container['copy_sell_to_addr_to_qte_from'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets at_odata_etag
     *
     * @return string|null
     */
    public function getAtOdataEtag()
    {
        return $this->container['at_odata_etag'];
    }

    /**
     * Sets at_odata_etag
     *
     * @param string|null $at_odata_etag If-Match header for updates
     *
     * @return self
     */
    public function setAtOdataEtag($at_odata_etag)
    {

        if (is_null($at_odata_etag)) {
            throw new \InvalidArgumentException('non-nullable at_odata_etag cannot be null');
        }

        $this->container['at_odata_etag'] = $at_odata_etag;

        return $this;
    }

    /**
     * Gets no
     *
     * @return string|null
     */
    public function getNo()
    {
        return $this->container['no'];
    }

    /**
     * Sets no
     *
     * @param string|null $no no
     *
     * @return self
     */
    public function setNo($no)
    {

        if (is_null($no)) {
            throw new \InvalidArgumentException('non-nullable no cannot be null');
        }

        $this->container['no'] = $no;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {

        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets search_name
     *
     * @return string|null
     */
    public function getSearchName()
    {
        return $this->container['search_name'];
    }

    /**
     * Sets search_name
     *
     * @param string|null $search_name search_name
     *
     * @return self
     */
    public function setSearchName($search_name)
    {

        if (is_null($search_name)) {
            throw new \InvalidArgumentException('non-nullable search_name cannot be null');
        }

        $this->container['search_name'] = $search_name;

        return $this;
    }

    /**
     * Gets name_2
     *
     * @return string|null
     */
    public function getName2()
    {
        return $this->container['name_2'];
    }

    /**
     * Sets name_2
     *
     * @param string|null $name_2 name_2
     *
     * @return self
     */
    public function setName2($name_2)
    {

        if (is_null($name_2)) {
            throw new \InvalidArgumentException('non-nullable name_2 cannot be null');
        }

        $this->container['name_2'] = $name_2;

        return $this;
    }

    /**
     * Gets address
     *
     * @return string|null
     */
    public function getAddress()
    {
        return $this->container['address'];
    }

    /**
     * Sets address
     *
     * @param string|null $address address
     *
     * @return self
     */
    public function setAddress($address)
    {

        if (is_null($address)) {
            throw new \InvalidArgumentException('non-nullable address cannot be null');
        }

        $this->container['address'] = $address;

        return $this;
    }

    /**
     * Gets address_2
     *
     * @return string|null
     */
    public function getAddress2()
    {
        return $this->container['address_2'];
    }

    /**
     * Sets address_2
     *
     * @param string|null $address_2 address_2
     *
     * @return self
     */
    public function setAddress2($address_2)
    {

        if (is_null($address_2)) {
            throw new \InvalidArgumentException('non-nullable address_2 cannot be null');
        }

        $this->container['address_2'] = $address_2;

        return $this;
    }

    /**
     * Gets city
     *
     * @return string|null
     */
    public function getCity()
    {
        return $this->container['city'];
    }

    /**
     * Sets city
     *
     * @param string|null $city city
     *
     * @return self
     */
    public function setCity($city)
    {

        if (is_null($city)) {
            throw new \InvalidArgumentException('non-nullable city cannot be null');
        }

        $this->container['city'] = $city;

        return $this;
    }

    /**
     * Gets contact_name
     *
     * @return string|null
     */
    public function getContactName()
    {
        return $this->container['contact_name'];
    }

    /**
     * Sets contact_name
     *
     * @param string|null $contact_name contact_name
     *
     * @return self
     */
    public function setContactName($contact_name)
    {

        if (is_null($contact_name)) {
            throw new \InvalidArgumentException('non-nullable contact_name cannot be null');
        }

        $this->container['contact_name'] = $contact_name;

        return $this;
    }

    /**
     * Gets phone_no
     *
     * @return string|null
     */
    public function getPhoneNo()
    {
        return $this->container['phone_no'];
    }

    /**
     * Sets phone_no
     *
     * @param string|null $phone_no phone_no
     *
     * @return self
     */
    public function setPhoneNo($phone_no)
    {

        if (is_null($phone_no)) {
            throw new \InvalidArgumentException('non-nullable phone_no cannot be null');
        }

        $this->container['phone_no'] = $phone_no;

        return $this;
    }

    /**
     * Gets document_sending_profile
     *
     * @return string|null
     */
    public function getDocumentSendingProfile()
    {
        return $this->container['document_sending_profile'];
    }

    /**
     * Sets document_sending_profile
     *
     * @param string|null $document_sending_profile document_sending_profile
     *
     * @return self
     */
    public function setDocumentSendingProfile($document_sending_profile)
    {

        if (is_null($document_sending_profile)) {
            throw new \InvalidArgumentException('non-nullable document_sending_profile cannot be null');
        }

        $this->container['document_sending_profile'] = $document_sending_profile;

        return $this;
    }

    /**
     * Gets ship_to_code
     *
     * @return string|null
     */
    public function getShipToCode()
    {
        return $this->container['ship_to_code'];
    }

    /**
     * Sets ship_to_code
     *
     * @param string|null $ship_to_code ship_to_code
     *
     * @return self
     */
    public function setShipToCode($ship_to_code)
    {

        if (is_null($ship_to_code)) {
            throw new \InvalidArgumentException('non-nullable ship_to_code cannot be null');
        }

        $this->container['ship_to_code'] = $ship_to_code;

        return $this;
    }

    /**
     * Gets global_dimension_1_code
     *
     * @return string|null
     */
    public function getGlobalDimension1Code()
    {
        return $this->container['global_dimension_1_code'];
    }

    /**
     * Sets global_dimension_1_code
     *
     * @param string|null $global_dimension_1_code global_dimension_1_code
     *
     * @return self
     */
    public function setGlobalDimension1Code($global_dimension_1_code)
    {

        if (is_null($global_dimension_1_code)) {
            throw new \InvalidArgumentException('non-nullable global_dimension_1_code cannot be null');
        }

        $this->container['global_dimension_1_code'] = $global_dimension_1_code;

        return $this;
    }

    /**
     * Gets global_dimension_2_code
     *
     * @return string|null
     */
    public function getGlobalDimension2Code()
    {
        return $this->container['global_dimension_2_code'];
    }

    /**
     * Sets global_dimension_2_code
     *
     * @param string|null $global_dimension_2_code global_dimension_2_code
     *
     * @return self
     */
    public function setGlobalDimension2Code($global_dimension_2_code)
    {

        if (is_null($global_dimension_2_code)) {
            throw new \InvalidArgumentException('non-nullable global_dimension_2_code cannot be null');
        }

        $this->container['global_dimension_2_code'] = $global_dimension_2_code;

        return $this;
    }

    /**
     * Gets credit_limit_lcy
     *
     * @return float|null
     */
    public function getCreditLimitLcy()
    {
        return $this->container['credit_limit_lcy'];
    }

    /**
     * Sets credit_limit_lcy
     *
     * @param float|null $credit_limit_lcy credit_limit_lcy
     *
     * @return self
     */
    public function setCreditLimitLcy($credit_limit_lcy)
    {

        if (is_null($credit_limit_lcy)) {
            throw new \InvalidArgumentException('non-nullable credit_limit_lcy cannot be null');
        }

        $this->container['credit_limit_lcy'] = $credit_limit_lcy;

        return $this;
    }

    /**
     * Gets customer_posting_group
     *
     * @return string|null
     */
    public function getCustomerPostingGroup()
    {
        return $this->container['customer_posting_group'];
    }

    /**
     * Sets customer_posting_group
     *
     * @param string|null $customer_posting_group customer_posting_group
     *
     * @return self
     */
    public function setCustomerPostingGroup($customer_posting_group)
    {

        if (is_null($customer_posting_group)) {
            throw new \InvalidArgumentException('non-nullable customer_posting_group cannot be null');
        }

        $this->container['customer_posting_group'] = $customer_posting_group;

        return $this;
    }

    /**
     * Gets currency_code
     *
     * @return string|null
     */
    public function getCurrencyCode()
    {
        return $this->container['currency_code'];
    }

    /**
     * Sets currency_code
     *
     * @param string|null $currency_code currency_code
     *
     * @return self
     */
    public function setCurrencyCode($currency_code)
    {

        if (is_null($currency_code)) {
            throw new \InvalidArgumentException('non-nullable currency_code cannot be null');
        }

        $this->container['currency_code'] = $currency_code;

        return $this;
    }

    /**
     * Gets customer_price_group
     *
     * @return string|null
     */
    public function getCustomerPriceGroup()
    {
        return $this->container['customer_price_group'];
    }

    /**
     * Sets customer_price_group
     *
     * @param string|null $customer_price_group customer_price_group
     *
     * @return self
     */
    public function setCustomerPriceGroup($customer_price_group)
    {

        if (is_null($customer_price_group)) {
            throw new \InvalidArgumentException('non-nullable customer_price_group cannot be null');
        }

        $this->container['customer_price_group'] = $customer_price_group;

        return $this;
    }

    /**
     * Gets language_code
     *
     * @return string|null
     */
    public function getLanguageCode()
    {
        return $this->container['language_code'];
    }

    /**
     * Sets language_code
     *
     * @param string|null $language_code language_code
     *
     * @return self
     */
    public function setLanguageCode($language_code)
    {

        if (is_null($language_code)) {
            throw new \InvalidArgumentException('non-nullable language_code cannot be null');
        }

        $this->container['language_code'] = $language_code;

        return $this;
    }

    /**
     * Gets payment_terms_code
     *
     * @return string|null
     */
    public function getPaymentTermsCode()
    {
        return $this->container['payment_terms_code'];
    }

    /**
     * Sets payment_terms_code
     *
     * @param string|null $payment_terms_code payment_terms_code
     *
     * @return self
     */
    public function setPaymentTermsCode($payment_terms_code)
    {

        if (is_null($payment_terms_code)) {
            throw new \InvalidArgumentException('non-nullable payment_terms_code cannot be null');
        }

        $this->container['payment_terms_code'] = $payment_terms_code;

        return $this;
    }

    /**
     * Gets fin_charge_terms_code
     *
     * @return string|null
     */
    public function getFinChargeTermsCode()
    {
        return $this->container['fin_charge_terms_code'];
    }

    /**
     * Sets fin_charge_terms_code
     *
     * @param string|null $fin_charge_terms_code fin_charge_terms_code
     *
     * @return self
     */
    public function setFinChargeTermsCode($fin_charge_terms_code)
    {

        if (is_null($fin_charge_terms_code)) {
            throw new \InvalidArgumentException('non-nullable fin_charge_terms_code cannot be null');
        }

        $this->container['fin_charge_terms_code'] = $fin_charge_terms_code;

        return $this;
    }

    /**
     * Gets salesperson_code
     *
     * @return string|null
     */
    public function getSalespersonCode()
    {
        return $this->container['salesperson_code'];
    }

    /**
     * Sets salesperson_code
     *
     * @param string|null $salesperson_code salesperson_code
     *
     * @return self
     */
    public function setSalespersonCode($salesperson_code)
    {

        if (is_null($salesperson_code)) {
            throw new \InvalidArgumentException('non-nullable salesperson_code cannot be null');
        }

        $this->container['salesperson_code'] = $salesperson_code;

        return $this;
    }

    /**
     * Gets shipment_method_code
     *
     * @return string|null
     */
    public function getShipmentMethodCode()
    {
        return $this->container['shipment_method_code'];
    }

    /**
     * Sets shipment_method_code
     *
     * @param string|null $shipment_method_code shipment_method_code
     *
     * @return self
     */
    public function setShipmentMethodCode($shipment_method_code)
    {

        if (is_null($shipment_method_code)) {
            throw new \InvalidArgumentException('non-nullable shipment_method_code cannot be null');
        }

        $this->container['shipment_method_code'] = $shipment_method_code;

        return $this;
    }

    /**
     * Gets shipping_agent_code
     *
     * @return string|null
     */
    public function getShippingAgentCode()
    {
        return $this->container['shipping_agent_code'];
    }

    /**
     * Sets shipping_agent_code
     *
     * @param string|null $shipping_agent_code shipping_agent_code
     *
     * @return self
     */
    public function setShippingAgentCode($shipping_agent_code)
    {

        if (is_null($shipping_agent_code)) {
            throw new \InvalidArgumentException('non-nullable shipping_agent_code cannot be null');
        }

        $this->container['shipping_agent_code'] = $shipping_agent_code;

        return $this;
    }

    /**
     * Gets invoice_disc_code
     *
     * @return string|null
     */
    public function getInvoiceDiscCode()
    {
        return $this->container['invoice_disc_code'];
    }

    /**
     * Sets invoice_disc_code
     *
     * @param string|null $invoice_disc_code invoice_disc_code
     *
     * @return self
     */
    public function setInvoiceDiscCode($invoice_disc_code)
    {

        if (is_null($invoice_disc_code)) {
            throw new \InvalidArgumentException('non-nullable invoice_disc_code cannot be null');
        }

        $this->container['invoice_disc_code'] = $invoice_disc_code;

        return $this;
    }

    /**
     * Gets customer_disc_group
     *
     * @return string|null
     */
    public function getCustomerDiscGroup()
    {
        return $this->container['customer_disc_group'];
    }

    /**
     * Sets customer_disc_group
     *
     * @param string|null $customer_disc_group customer_disc_group
     *
     * @return self
     */
    public function setCustomerDiscGroup($customer_disc_group)
    {

        if (is_null($customer_disc_group)) {
            throw new \InvalidArgumentException('non-nullable customer_disc_group cannot be null');
        }

        $this->container['customer_disc_group'] = $customer_disc_group;

        return $this;
    }

    /**
     * Gets country_region_code
     *
     * @return string|null
     */
    public function getCountryRegionCode()
    {
        return $this->container['country_region_code'];
    }

    /**
     * Sets country_region_code
     *
     * @param string|null $country_region_code country_region_code
     *
     * @return self
     */
    public function setCountryRegionCode($country_region_code)
    {

        if (is_null($country_region_code)) {
            throw new \InvalidArgumentException('non-nullable country_region_code cannot be null');
        }

        $this->container['country_region_code'] = $country_region_code;

        return $this;
    }

    /**
     * Gets blocked
     *
     * @return string|null
     */
    public function getBlocked()
    {
        return $this->container['blocked'];
    }

    /**
     * Sets blocked
     *
     * @param string|null $blocked blocked
     *
     * @return self
     */
    public function setBlocked($blocked)
    {
        $allowedValues = $this->getBlockedAllowableValues();
        if (!is_null($blocked) && !in_array($blocked, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'blocked', must be one of '%s'",
                    $blocked,
                    implode("', '", $allowedValues)
                )
            );
        }

        if (is_null($blocked)) {
            throw new \InvalidArgumentException('non-nullable blocked cannot be null');
        }

        $this->container['blocked'] = $blocked;

        return $this;
    }

    /**
     * Gets invoice_copies
     *
     * @return int|null
     */
    public function getInvoiceCopies()
    {
        return $this->container['invoice_copies'];
    }

    /**
     * Sets invoice_copies
     *
     * @param int|null $invoice_copies invoice_copies
     *
     * @return self
     */
    public function setInvoiceCopies($invoice_copies)
    {

        if (is_null($invoice_copies)) {
            throw new \InvalidArgumentException('non-nullable invoice_copies cannot be null');
        }

        $this->container['invoice_copies'] = $invoice_copies;

        return $this;
    }

    /**
     * Gets last_statement_no
     *
     * @return int|null
     */
    public function getLastStatementNo()
    {
        return $this->container['last_statement_no'];
    }

    /**
     * Sets last_statement_no
     *
     * @param int|null $last_statement_no last_statement_no
     *
     * @return self
     */
    public function setLastStatementNo($last_statement_no)
    {

        if (is_null($last_statement_no)) {
            throw new \InvalidArgumentException('non-nullable last_statement_no cannot be null');
        }

        $this->container['last_statement_no'] = $last_statement_no;

        return $this;
    }

    /**
     * Gets print_statements
     *
     * @return bool|null
     */
    public function getPrintStatements()
    {
        return $this->container['print_statements'];
    }

    /**
     * Sets print_statements
     *
     * @param bool|null $print_statements print_statements
     *
     * @return self
     */
    public function setPrintStatements($print_statements)
    {

        if (is_null($print_statements)) {
            throw new \InvalidArgumentException('non-nullable print_statements cannot be null');
        }

        $this->container['print_statements'] = $print_statements;

        return $this;
    }

    /**
     * Gets bill_to_customer_no
     *
     * @return string|null
     */
    public function getBillToCustomerNo()
    {
        return $this->container['bill_to_customer_no'];
    }

    /**
     * Sets bill_to_customer_no
     *
     * @param string|null $bill_to_customer_no bill_to_customer_no
     *
     * @return self
     */
    public function setBillToCustomerNo($bill_to_customer_no)
    {

        if (is_null($bill_to_customer_no)) {
            throw new \InvalidArgumentException('non-nullable bill_to_customer_no cannot be null');
        }

        $this->container['bill_to_customer_no'] = $bill_to_customer_no;

        return $this;
    }

    /**
     * Gets payment_method_code
     *
     * @return string|null
     */
    public function getPaymentMethodCode()
    {
        return $this->container['payment_method_code'];
    }

    /**
     * Sets payment_method_code
     *
     * @param string|null $payment_method_code payment_method_code
     *
     * @return self
     */
    public function setPaymentMethodCode($payment_method_code)
    {

        if (is_null($payment_method_code)) {
            throw new \InvalidArgumentException('non-nullable payment_method_code cannot be null');
        }

        $this->container['payment_method_code'] = $payment_method_code;

        return $this;
    }

    /**
     * Gets last_date_modified
     *
     * @return string|null
     */
    public function getLastDateModified()
    {
        return $this->container['last_date_modified'];
    }

    /**
     * Sets last_date_modified
     *
     * @param string|null $last_date_modified last_date_modified
     *
     * @return self
     */
    public function setLastDateModified($last_date_modified)
    {

        if (is_null($last_date_modified)) {
            throw new \InvalidArgumentException('non-nullable last_date_modified cannot be null');
        }

        $this->container['last_date_modified'] = $last_date_modified;

        return $this;
    }

    /**
     * Gets balance_lcy
     *
     * @return float|null
     */
    public function getBalanceLcy()
    {
        return $this->container['balance_lcy'];
    }

    /**
     * Sets balance_lcy
     *
     * @param float|null $balance_lcy balance_lcy
     *
     * @return self
     */
    public function setBalanceLcy($balance_lcy)
    {

        if (is_null($balance_lcy)) {
            throw new \InvalidArgumentException('non-nullable balance_lcy cannot be null');
        }

        $this->container['balance_lcy'] = $balance_lcy;

        return $this;
    }

    /**
     * Gets balance_due_lcy
     *
     * @return float|null
     */
    public function getBalanceDueLcy()
    {
        return $this->container['balance_due_lcy'];
    }

    /**
     * Sets balance_due_lcy
     *
     * @param float|null $balance_due_lcy balance_due_lcy
     *
     * @return self
     */
    public function setBalanceDueLcy($balance_due_lcy)
    {

        if (is_null($balance_due_lcy)) {
            throw new \InvalidArgumentException('non-nullable balance_due_lcy cannot be null');
        }

        $this->container['balance_due_lcy'] = $balance_due_lcy;

        return $this;
    }

    /**
     * Gets cr_memo_amounts_lcy
     *
     * @return float|null
     */
    public function getCrMemoAmountsLcy()
    {
        return $this->container['cr_memo_amounts_lcy'];
    }

    /**
     * Sets cr_memo_amounts_lcy
     *
     * @param float|null $cr_memo_amounts_lcy cr_memo_amounts_lcy
     *
     * @return self
     */
    public function setCrMemoAmountsLcy($cr_memo_amounts_lcy)
    {

        if (is_null($cr_memo_amounts_lcy)) {
            throw new \InvalidArgumentException('non-nullable cr_memo_amounts_lcy cannot be null');
        }

        $this->container['cr_memo_amounts_lcy'] = $cr_memo_amounts_lcy;

        return $this;
    }

    /**
     * Gets application_method
     *
     * @return string|null
     */
    public function getApplicationMethod()
    {
        return $this->container['application_method'];
    }

    /**
     * Sets application_method
     *
     * @param string|null $application_method application_method
     *
     * @return self
     */
    public function setApplicationMethod($application_method)
    {
        $allowedValues = $this->getApplicationMethodAllowableValues();
        if (!is_null($application_method) && !in_array($application_method, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'application_method', must be one of '%s'",
                    $application_method,
                    implode("', '", $allowedValues)
                )
            );
        }

        if (is_null($application_method)) {
            throw new \InvalidArgumentException('non-nullable application_method cannot be null');
        }

        $this->container['application_method'] = $application_method;

        return $this;
    }

    /**
     * Gets prices_including_vat
     *
     * @return bool|null
     */
    public function getPricesIncludingVat()
    {
        return $this->container['prices_including_vat'];
    }

    /**
     * Sets prices_including_vat
     *
     * @param bool|null $prices_including_vat prices_including_vat
     *
     * @return self
     */
    public function setPricesIncludingVat($prices_including_vat)
    {

        if (is_null($prices_including_vat)) {
            throw new \InvalidArgumentException('non-nullable prices_including_vat cannot be null');
        }

        $this->container['prices_including_vat'] = $prices_including_vat;

        return $this;
    }

    /**
     * Gets location_code
     *
     * @return string|null
     */
    public function getLocationCode()
    {
        return $this->container['location_code'];
    }

    /**
     * Sets location_code
     *
     * @param string|null $location_code location_code
     *
     * @return self
     */
    public function setLocationCode($location_code)
    {

        if (is_null($location_code)) {
            throw new \InvalidArgumentException('non-nullable location_code cannot be null');
        }

        $this->container['location_code'] = $location_code;

        return $this;
    }

    /**
     * Gets fax_no
     *
     * @return string|null
     */
    public function getFaxNo()
    {
        return $this->container['fax_no'];
    }

    /**
     * Sets fax_no
     *
     * @param string|null $fax_no fax_no
     *
     * @return self
     */
    public function setFaxNo($fax_no)
    {

        if (is_null($fax_no)) {
            throw new \InvalidArgumentException('non-nullable fax_no cannot be null');
        }

        $this->container['fax_no'] = $fax_no;

        return $this;
    }

    /**
     * Gets vat_registration_no
     *
     * @return string|null
     */
    public function getVatRegistrationNo()
    {
        return $this->container['vat_registration_no'];
    }

    /**
     * Sets vat_registration_no
     *
     * @param string|null $vat_registration_no vat_registration_no
     *
     * @return self
     */
    public function setVatRegistrationNo($vat_registration_no)
    {

        if (is_null($vat_registration_no)) {
            throw new \InvalidArgumentException('non-nullable vat_registration_no cannot be null');
        }

        $this->container['vat_registration_no'] = $vat_registration_no;

        return $this;
    }

    /**
     * Gets combine_shipments
     *
     * @return bool|null
     */
    public function getCombineShipments()
    {
        return $this->container['combine_shipments'];
    }

    /**
     * Sets combine_shipments
     *
     * @param bool|null $combine_shipments combine_shipments
     *
     * @return self
     */
    public function setCombineShipments($combine_shipments)
    {

        if (is_null($combine_shipments)) {
            throw new \InvalidArgumentException('non-nullable combine_shipments cannot be null');
        }

        $this->container['combine_shipments'] = $combine_shipments;

        return $this;
    }

    /**
     * Gets gen_bus_posting_group
     *
     * @return string|null
     */
    public function getGenBusPostingGroup()
    {
        return $this->container['gen_bus_posting_group'];
    }

    /**
     * Sets gen_bus_posting_group
     *
     * @param string|null $gen_bus_posting_group gen_bus_posting_group
     *
     * @return self
     */
    public function setGenBusPostingGroup($gen_bus_posting_group)
    {

        if (is_null($gen_bus_posting_group)) {
            throw new \InvalidArgumentException('non-nullable gen_bus_posting_group cannot be null');
        }

        $this->container['gen_bus_posting_group'] = $gen_bus_posting_group;

        return $this;
    }

    /**
     * Gets gln
     *
     * @return string|null
     */
    public function getGln()
    {
        return $this->container['gln'];
    }

    /**
     * Sets gln
     *
     * @param string|null $gln gln
     *
     * @return self
     */
    public function setGln($gln)
    {

        if (is_null($gln)) {
            throw new \InvalidArgumentException('non-nullable gln cannot be null');
        }

        $this->container['gln'] = $gln;

        return $this;
    }

    /**
     * Gets post_code
     *
     * @return string|null
     */
    public function getPostCode()
    {
        return $this->container['post_code'];
    }

    /**
     * Sets post_code
     *
     * @param string|null $post_code post_code
     *
     * @return self
     */
    public function setPostCode($post_code)
    {

        if (is_null($post_code)) {
            throw new \InvalidArgumentException('non-nullable post_code cannot be null');
        }

        $this->container['post_code'] = $post_code;

        return $this;
    }

    /**
     * Gets county
     *
     * @return string|null
     */
    public function getCounty()
    {
        return $this->container['county'];
    }

    /**
     * Sets county
     *
     * @param string|null $county county
     *
     * @return self
     */
    public function setCounty($county)
    {

        if (is_null($county)) {
            throw new \InvalidArgumentException('non-nullable county cannot be null');
        }

        $this->container['county'] = $county;

        return $this;
    }

    /**
     * Gets eori_number
     *
     * @return string|null
     */
    public function getEoriNumber()
    {
        return $this->container['eori_number'];
    }

    /**
     * Sets eori_number
     *
     * @param string|null $eori_number eori_number
     *
     * @return self
     */
    public function setEoriNumber($eori_number)
    {

        if (is_null($eori_number)) {
            throw new \InvalidArgumentException('non-nullable eori_number cannot be null');
        }

        $this->container['eori_number'] = $eori_number;

        return $this;
    }

    /**
     * Gets use_gln_in_electronic_document
     *
     * @return bool|null
     */
    public function getUseGlnInElectronicDocument()
    {
        return $this->container['use_gln_in_electronic_document'];
    }

    /**
     * Sets use_gln_in_electronic_document
     *
     * @param bool|null $use_gln_in_electronic_document use_gln_in_electronic_document
     *
     * @return self
     */
    public function setUseGlnInElectronicDocument($use_gln_in_electronic_document)
    {

        if (is_null($use_gln_in_electronic_document)) {
            throw new \InvalidArgumentException('non-nullable use_gln_in_electronic_document cannot be null');
        }

        $this->container['use_gln_in_electronic_document'] = $use_gln_in_electronic_document;

        return $this;
    }

    /**
     * Gets e_mail
     *
     * @return string|null
     */
    public function getEMail()
    {
        return $this->container['e_mail'];
    }

    /**
     * Sets e_mail
     *
     * @param string|null $e_mail e_mail
     *
     * @return self
     */
    public function setEMail($e_mail)
    {

        if (is_null($e_mail)) {
            throw new \InvalidArgumentException('non-nullable e_mail cannot be null');
        }

        $this->container['e_mail'] = $e_mail;

        return $this;
    }

    /**
     * Gets home_page
     *
     * @return string|null
     */
    public function getHomePage()
    {
        return $this->container['home_page'];
    }

    /**
     * Sets home_page
     *
     * @param string|null $home_page home_page
     *
     * @return self
     */
    public function setHomePage($home_page)
    {

        if (is_null($home_page)) {
            throw new \InvalidArgumentException('non-nullable home_page cannot be null');
        }

        $this->container['home_page'] = $home_page;

        return $this;
    }

    /**
     * Gets reminder_terms_code
     *
     * @return string|null
     */
    public function getReminderTermsCode()
    {
        return $this->container['reminder_terms_code'];
    }

    /**
     * Sets reminder_terms_code
     *
     * @param string|null $reminder_terms_code reminder_terms_code
     *
     * @return self
     */
    public function setReminderTermsCode($reminder_terms_code)
    {

        if (is_null($reminder_terms_code)) {
            throw new \InvalidArgumentException('non-nullable reminder_terms_code cannot be null');
        }

        $this->container['reminder_terms_code'] = $reminder_terms_code;

        return $this;
    }

    /**
     * Gets tax_area_code
     *
     * @return string|null
     */
    public function getTaxAreaCode()
    {
        return $this->container['tax_area_code'];
    }

    /**
     * Sets tax_area_code
     *
     * @param string|null $tax_area_code tax_area_code
     *
     * @return self
     */
    public function setTaxAreaCode($tax_area_code)
    {

        if (is_null($tax_area_code)) {
            throw new \InvalidArgumentException('non-nullable tax_area_code cannot be null');
        }

        $this->container['tax_area_code'] = $tax_area_code;

        return $this;
    }

    /**
     * Gets tax_liable
     *
     * @return bool|null
     */
    public function getTaxLiable()
    {
        return $this->container['tax_liable'];
    }

    /**
     * Sets tax_liable
     *
     * @param bool|null $tax_liable tax_liable
     *
     * @return self
     */
    public function setTaxLiable($tax_liable)
    {

        if (is_null($tax_liable)) {
            throw new \InvalidArgumentException('non-nullable tax_liable cannot be null');
        }

        $this->container['tax_liable'] = $tax_liable;

        return $this;
    }

    /**
     * Gets vat_bus_posting_group
     *
     * @return string|null
     */
    public function getVatBusPostingGroup()
    {
        return $this->container['vat_bus_posting_group'];
    }

    /**
     * Sets vat_bus_posting_group
     *
     * @param string|null $vat_bus_posting_group vat_bus_posting_group
     *
     * @return self
     */
    public function setVatBusPostingGroup($vat_bus_posting_group)
    {

        if (is_null($vat_bus_posting_group)) {
            throw new \InvalidArgumentException('non-nullable vat_bus_posting_group cannot be null');
        }

        $this->container['vat_bus_posting_group'] = $vat_bus_posting_group;

        return $this;
    }

    /**
     * Gets reserve
     *
     * @return string|null
     */
    public function getReserve()
    {
        return $this->container['reserve'];
    }

    /**
     * Sets reserve
     *
     * @param string|null $reserve reserve
     *
     * @return self
     */
    public function setReserve($reserve)
    {
        $allowedValues = $this->getReserveAllowableValues();
        if (!is_null($reserve) && !in_array($reserve, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'reserve', must be one of '%s'",
                    $reserve,
                    implode("', '", $allowedValues)
                )
            );
        }

        if (is_null($reserve)) {
            throw new \InvalidArgumentException('non-nullable reserve cannot be null');
        }

        $this->container['reserve'] = $reserve;

        return $this;
    }

    /**
     * Gets block_payment_tolerance
     *
     * @return bool|null
     */
    public function getBlockPaymentTolerance()
    {
        return $this->container['block_payment_tolerance'];
    }

    /**
     * Sets block_payment_tolerance
     *
     * @param bool|null $block_payment_tolerance block_payment_tolerance
     *
     * @return self
     */
    public function setBlockPaymentTolerance($block_payment_tolerance)
    {

        if (is_null($block_payment_tolerance)) {
            throw new \InvalidArgumentException('non-nullable block_payment_tolerance cannot be null');
        }

        $this->container['block_payment_tolerance'] = $block_payment_tolerance;

        return $this;
    }

    /**
     * Gets ic_partner_code
     *
     * @return string|null
     */
    public function getIcPartnerCode()
    {
        return $this->container['ic_partner_code'];
    }

    /**
     * Sets ic_partner_code
     *
     * @param string|null $ic_partner_code ic_partner_code
     *
     * @return self
     */
    public function setIcPartnerCode($ic_partner_code)
    {

        if (is_null($ic_partner_code)) {
            throw new \InvalidArgumentException('non-nullable ic_partner_code cannot be null');
        }

        $this->container['ic_partner_code'] = $ic_partner_code;

        return $this;
    }

    /**
     * Gets prepayment_percent
     *
     * @return float|null
     */
    public function getPrepaymentPercent()
    {
        return $this->container['prepayment_percent'];
    }

    /**
     * Sets prepayment_percent
     *
     * @param float|null $prepayment_percent prepayment_percent
     *
     * @return self
     */
    public function setPrepaymentPercent($prepayment_percent)
    {

        if (is_null($prepayment_percent)) {
            throw new \InvalidArgumentException('non-nullable prepayment_percent cannot be null');
        }

        $this->container['prepayment_percent'] = $prepayment_percent;

        return $this;
    }

    /**
     * Gets outstanding_invoices_lcy
     *
     * @return float|null
     */
    public function getOutstandingInvoicesLcy()
    {
        return $this->container['outstanding_invoices_lcy'];
    }

    /**
     * Sets outstanding_invoices_lcy
     *
     * @param float|null $outstanding_invoices_lcy outstanding_invoices_lcy
     *
     * @return self
     */
    public function setOutstandingInvoicesLcy($outstanding_invoices_lcy)
    {

        if (is_null($outstanding_invoices_lcy)) {
            throw new \InvalidArgumentException('non-nullable outstanding_invoices_lcy cannot be null');
        }

        $this->container['outstanding_invoices_lcy'] = $outstanding_invoices_lcy;

        return $this;
    }

    /**
     * Gets partner_type
     *
     * @return string|null
     */
    public function getPartnerType()
    {
        return $this->container['partner_type'];
    }

    /**
     * Sets partner_type
     *
     * @param string|null $partner_type partner_type
     *
     * @return self
     */
    public function setPartnerType($partner_type)
    {
        $allowedValues = $this->getPartnerTypeAllowableValues();
        if (!is_null($partner_type) && !in_array($partner_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'partner_type', must be one of '%s'",
                    $partner_type,
                    implode("', '", $allowedValues)
                )
            );
        }

        if (is_null($partner_type)) {
            throw new \InvalidArgumentException('non-nullable partner_type cannot be null');
        }

        $this->container['partner_type'] = $partner_type;

        return $this;
    }

    /**
     * Gets privacy_blocked
     *
     * @return bool|null
     */
    public function getPrivacyBlocked()
    {
        return $this->container['privacy_blocked'];
    }

    /**
     * Sets privacy_blocked
     *
     * @param bool|null $privacy_blocked privacy_blocked
     *
     * @return self
     */
    public function setPrivacyBlocked($privacy_blocked)
    {

        if (is_null($privacy_blocked)) {
            throw new \InvalidArgumentException('non-nullable privacy_blocked cannot be null');
        }

        $this->container['privacy_blocked'] = $privacy_blocked;

        return $this;
    }

    /**
     * Gets disable_search_by_name
     *
     * @return bool|null
     */
    public function getDisableSearchByName()
    {
        return $this->container['disable_search_by_name'];
    }

    /**
     * Sets disable_search_by_name
     *
     * @param bool|null $disable_search_by_name disable_search_by_name
     *
     * @return self
     */
    public function setDisableSearchByName($disable_search_by_name)
    {

        if (is_null($disable_search_by_name)) {
            throw new \InvalidArgumentException('non-nullable disable_search_by_name cannot be null');
        }

        $this->container['disable_search_by_name'] = $disable_search_by_name;

        return $this;
    }

    /**
     * Gets preferred_bank_account_code
     *
     * @return string|null
     */
    public function getPreferredBankAccountCode()
    {
        return $this->container['preferred_bank_account_code'];
    }

    /**
     * Sets preferred_bank_account_code
     *
     * @param string|null $preferred_bank_account_code preferred_bank_account_code
     *
     * @return self
     */
    public function setPreferredBankAccountCode($preferred_bank_account_code)
    {

        if (is_null($preferred_bank_account_code)) {
            throw new \InvalidArgumentException('non-nullable preferred_bank_account_code cannot be null');
        }

        $this->container['preferred_bank_account_code'] = $preferred_bank_account_code;

        return $this;
    }

    /**
     * Gets cash_flow_payment_terms_code
     *
     * @return string|null
     */
    public function getCashFlowPaymentTermsCode()
    {
        return $this->container['cash_flow_payment_terms_code'];
    }

    /**
     * Sets cash_flow_payment_terms_code
     *
     * @param string|null $cash_flow_payment_terms_code cash_flow_payment_terms_code
     *
     * @return self
     */
    public function setCashFlowPaymentTermsCode($cash_flow_payment_terms_code)
    {

        if (is_null($cash_flow_payment_terms_code)) {
            throw new \InvalidArgumentException('non-nullable cash_flow_payment_terms_code cannot be null');
        }

        $this->container['cash_flow_payment_terms_code'] = $cash_flow_payment_terms_code;

        return $this;
    }

    /**
     * Gets primary_contact_no
     *
     * @return string|null
     */
    public function getPrimaryContactNo()
    {
        return $this->container['primary_contact_no'];
    }

    /**
     * Sets primary_contact_no
     *
     * @param string|null $primary_contact_no primary_contact_no
     *
     * @return self
     */
    public function setPrimaryContactNo($primary_contact_no)
    {

        if (is_null($primary_contact_no)) {
            throw new \InvalidArgumentException('non-nullable primary_contact_no cannot be null');
        }

        $this->container['primary_contact_no'] = $primary_contact_no;

        return $this;
    }

    /**
     * Gets mobile_phone_no
     *
     * @return string|null
     */
    public function getMobilePhoneNo()
    {
        return $this->container['mobile_phone_no'];
    }

    /**
     * Sets mobile_phone_no
     *
     * @param string|null $mobile_phone_no mobile_phone_no
     *
     * @return self
     */
    public function setMobilePhoneNo($mobile_phone_no)
    {

        if (is_null($mobile_phone_no)) {
            throw new \InvalidArgumentException('non-nullable mobile_phone_no cannot be null');
        }

        $this->container['mobile_phone_no'] = $mobile_phone_no;

        return $this;
    }

    /**
     * Gets responsibility_center
     *
     * @return string|null
     */
    public function getResponsibilityCenter()
    {
        return $this->container['responsibility_center'];
    }

    /**
     * Sets responsibility_center
     *
     * @param string|null $responsibility_center responsibility_center
     *
     * @return self
     */
    public function setResponsibilityCenter($responsibility_center)
    {

        if (is_null($responsibility_center)) {
            throw new \InvalidArgumentException('non-nullable responsibility_center cannot be null');
        }

        $this->container['responsibility_center'] = $responsibility_center;

        return $this;
    }

    /**
     * Gets shipping_advice
     *
     * @return string|null
     */
    public function getShippingAdvice()
    {
        return $this->container['shipping_advice'];
    }

    /**
     * Sets shipping_advice
     *
     * @param string|null $shipping_advice shipping_advice
     *
     * @return self
     */
    public function setShippingAdvice($shipping_advice)
    {
        $allowedValues = $this->getShippingAdviceAllowableValues();
        if (!is_null($shipping_advice) && !in_array($shipping_advice, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'shipping_advice', must be one of '%s'",
                    $shipping_advice,
                    implode("', '", $allowedValues)
                )
            );
        }

        if (is_null($shipping_advice)) {
            throw new \InvalidArgumentException('non-nullable shipping_advice cannot be null');
        }

        $this->container['shipping_advice'] = $shipping_advice;

        return $this;
    }

    /**
     * Gets shipping_time
     *
     * @return string|null
     */
    public function getShippingTime()
    {
        return $this->container['shipping_time'];
    }

    /**
     * Sets shipping_time
     *
     * @param string|null $shipping_time shipping_time
     *
     * @return self
     */
    public function setShippingTime($shipping_time)
    {

        if (is_null($shipping_time)) {
            throw new \InvalidArgumentException('non-nullable shipping_time cannot be null');
        }

        $this->container['shipping_time'] = $shipping_time;

        return $this;
    }

    /**
     * Gets service_zone_code
     *
     * @return string|null
     */
    public function getServiceZoneCode()
    {
        return $this->container['service_zone_code'];
    }

    /**
     * Sets service_zone_code
     *
     * @param string|null $service_zone_code service_zone_code
     *
     * @return self
     */
    public function setServiceZoneCode($service_zone_code)
    {

        if (is_null($service_zone_code)) {
            throw new \InvalidArgumentException('non-nullable service_zone_code cannot be null');
        }

        $this->container['service_zone_code'] = $service_zone_code;

        return $this;
    }

    /**
     * Gets price_calculation_method
     *
     * @return string|null
     */
    public function getPriceCalculationMethod()
    {
        return $this->container['price_calculation_method'];
    }

    /**
     * Sets price_calculation_method
     *
     * @param string|null $price_calculation_method price_calculation_method
     *
     * @return self
     */
    public function setPriceCalculationMethod($price_calculation_method)
    {
        $allowedValues = $this->getPriceCalculationMethodAllowableValues();
        if (!is_null($price_calculation_method) && !in_array($price_calculation_method, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'price_calculation_method', must be one of '%s'",
                    $price_calculation_method,
                    implode("', '", $allowedValues)
                )
            );
        }

        if (is_null($price_calculation_method)) {
            throw new \InvalidArgumentException('non-nullable price_calculation_method cannot be null');
        }

        $this->container['price_calculation_method'] = $price_calculation_method;

        return $this;
    }

    /**
     * Gets allow_line_disc
     *
     * @return bool|null
     */
    public function getAllowLineDisc()
    {
        return $this->container['allow_line_disc'];
    }

    /**
     * Sets allow_line_disc
     *
     * @param bool|null $allow_line_disc allow_line_disc
     *
     * @return self
     */
    public function setAllowLineDisc($allow_line_disc)
    {

        if (is_null($allow_line_disc)) {
            throw new \InvalidArgumentException('non-nullable allow_line_disc cannot be null');
        }

        $this->container['allow_line_disc'] = $allow_line_disc;

        return $this;
    }

    /**
     * Gets base_calendar_code
     *
     * @return string|null
     */
    public function getBaseCalendarCode()
    {
        return $this->container['base_calendar_code'];
    }

    /**
     * Sets base_calendar_code
     *
     * @param string|null $base_calendar_code base_calendar_code
     *
     * @return self
     */
    public function setBaseCalendarCode($base_calendar_code)
    {

        if (is_null($base_calendar_code)) {
            throw new \InvalidArgumentException('non-nullable base_calendar_code cannot be null');
        }

        $this->container['base_calendar_code'] = $base_calendar_code;

        return $this;
    }

    /**
     * Gets copy_sell_to_addr_to_qte_from
     *
     * @return string|null
     */
    public function getCopySellToAddrToQteFrom()
    {
        return $this->container['copy_sell_to_addr_to_qte_from'];
    }

    /**
     * Sets copy_sell_to_addr_to_qte_from
     *
     * @param string|null $copy_sell_to_addr_to_qte_from copy_sell_to_addr_to_qte_from
     *
     * @return self
     */
    public function setCopySellToAddrToQteFrom($copy_sell_to_addr_to_qte_from)
    {
        $allowedValues = $this->getCopySellToAddrToQteFromAllowableValues();
        if (!is_null($copy_sell_to_addr_to_qte_from) && !in_array($copy_sell_to_addr_to_qte_from, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'copy_sell_to_addr_to_qte_from', must be one of '%s'",
                    $copy_sell_to_addr_to_qte_from,
                    implode("', '", $allowedValues)
                )
            );
        }

        if (is_null($copy_sell_to_addr_to_qte_from)) {
            throw new \InvalidArgumentException('non-nullable copy_sell_to_addr_to_qte_from cannot be null');
        }

        $this->container['copy_sell_to_addr_to_qte_from'] = $copy_sell_to_addr_to_qte_from;

        return $this;
    }

    /**
     * Gets balance_due
     *
     * @return float|null
     */
    public function getBalanceDue()
    {
        return $this->container['balance_due'];
    }

    /**
     * Sets balance_due
     *
     * @param float|null $balance_due balance_due
     *
     * @return self
     */
    public function setBalanceDue($balance_due)
    {

        if (is_null($balance_due)) {
            throw new \InvalidArgumentException('non-nullable balance_due cannot be null');
        }

        $this->container['balance_due'] = $balance_due;

        return $this;
    }

    /**
     * Gets shipping_agent_service_code
     *
     * @return string|null
     */
    public function getShippingAgentServiceCode()
    {
        return $this->container['shipping_agent_service_code'];
    }

    /**
     * Sets shipping_agent_service_code
     *
     * @param string|null $shipping_agent_service_code shipping_agent_service_code
     *
     * @return self
     */
    public function setShippingAgentServiceCode($shipping_agent_service_code)
    {

        if (is_null($shipping_agent_service_code)) {
            throw new \InvalidArgumentException('non-nullable shipping_agent_service_code cannot be null');
        }

        $this->container['shipping_agent_service_code'] = $shipping_agent_service_code;

        return $this;
    }

    /**
     * Gets global_dimension_1_filter
     *
     * @return string|null
     */
    public function getGlobalDimension1Filter()
    {
        return $this->container['global_dimension_1_filter'];
    }

    /**
     * Sets global_dimension_1_filter
     *
     * @param string|null $global_dimension_1_filter global_dimension_1_filter
     *
     * @return self
     */
    public function setGlobalDimension1Filter($global_dimension_1_filter)
    {

        if (is_null($global_dimension_1_filter)) {
            throw new \InvalidArgumentException('non-nullable global_dimension_1_filter cannot be null');
        }

        $this->container['global_dimension_1_filter'] = $global_dimension_1_filter;

        return $this;
    }

    /**
     * Gets global_dimension_2_filter
     *
     * @return string|null
     */
    public function getGlobalDimension2Filter()
    {
        return $this->container['global_dimension_2_filter'];
    }

    /**
     * Sets global_dimension_2_filter
     *
     * @param string|null $global_dimension_2_filter global_dimension_2_filter
     *
     * @return self
     */
    public function setGlobalDimension2Filter($global_dimension_2_filter)
    {

        if (is_null($global_dimension_2_filter)) {
            throw new \InvalidArgumentException('non-nullable global_dimension_2_filter cannot be null');
        }

        $this->container['global_dimension_2_filter'] = $global_dimension_2_filter;

        return $this;
    }

    /**
     * Gets currency_filter
     *
     * @return string|null
     */
    public function getCurrencyFilter()
    {
        return $this->container['currency_filter'];
    }

    /**
     * Sets currency_filter
     *
     * @param string|null $currency_filter currency_filter
     *
     * @return self
     */
    public function setCurrencyFilter($currency_filter)
    {

        if (is_null($currency_filter)) {
            throw new \InvalidArgumentException('non-nullable currency_filter cannot be null');
        }

        $this->container['currency_filter'] = $currency_filter;

        return $this;
    }

    /**
     * Gets date_filter
     *
     * @return string|null
     */
    public function getDateFilter()
    {
        return $this->container['date_filter'];
    }

    /**
     * Sets date_filter
     *
     * @param string|null $date_filter date_filter
     *
     * @return self
     */
    public function setDateFilter($date_filter)
    {

        if (is_null($date_filter)) {
            throw new \InvalidArgumentException('non-nullable date_filter cannot be null');
        }

        $this->container['date_filter'] = $date_filter;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return (string)json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


