<?php
/**
 * SpyDefaultDimensionModelFields
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Spy\MsbcRestClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Microsoft Business Center API
 *
 * Generated by: https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Spy\MsbcRestClient\Model;

/**
 * SpyDefaultDimensionModelFields Class Doc Comment
 *
 * @category Class
 * @package  Spy\MsbcRestClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SpyDefaultDimensionModelFields
{
    public string $strAtOdataEtag = '@odata.etag';
    public string $strTableId = 'Table_ID';
    public string $strNo = 'No';
    public string $strDimensionCode = 'Dimension_Code';
    public string $strDimensionValueCode = 'Dimension_Value_Code';
    public string $strValuePosting = 'Value_Posting';
}

