<?php
/**
 * SpyGeneralLedgerSetupModelFields
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Spy\MsbcRestClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Microsoft Business Center API
 *
 * Generated by: https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Spy\MsbcRestClient\Model;

/**
 * SpyGeneralLedgerSetupModelFields Class Doc Comment
 *
 * @category Class
 * @package  Spy\MsbcRestClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SpyGeneralLedgerSetupModelFields
{
    public string $strAtOdataEtag = '@odata.etag';
    public string $strSystemId = 'systemId';
    public string $strSystemCreatedAt = 'systemCreatedAt';
    public string $strSystemCreatedBy = 'systemCreatedBy';
    public string $strSystemModifiedAt = 'systemModifiedAt';
    public string $strSystemModifiedBy = 'systemModifiedBy';
    public string $strAllowPostingFromDate = 'allowPostingFromDate';
    public string $strAllowPostingToDate = 'allowPostingToDate';
}

