<?php
/**
 * SpyLedgerTrans
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Spy\MsbcRestClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Microsoft Business Center API
 *
 * The Microsoft Business Center API is a RESTful API that provides an interface to the Microsoft Business Center service.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Spy\MsbcRestClient\Model;

use \ArrayAccess;
use \Spy\MsbcRestClient\ObjectSerializer;

/**
 * SpyLedgerTrans Class Doc Comment
 *
 * @category Class
 * @package  Spy\MsbcRestClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SpyLedgerTrans implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * Return an object with the Model Fields
      *
      * @return SpyLedgerTransModelFields
      */
    public static function GetModelFields(): SpyLedgerTransModelFields
    {
        return new SpyLedgerTransModelFields();
    }

    /**
      * Return an object with the Model Attributes
      *
      * @return SpyLedgerTransModelAttributes
      */
    public static function GetModelAttributes(): SpyLedgerTransModelAttributes
    {
        return new SpyLedgerTransModelAttributes();
    }

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SpyLedgerTrans';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'at_odata_etag' => 'string',
        'entry_no' => 'int',
        'posting_date' => 'string',
        'document_type' => 'string',
        'document_no' => 'string',
        'g_l_account_no' => 'string',
        'g_l_account_name' => 'string',
        'description' => 'string',
        'job_no' => 'string',
        'global_dimension_1_code' => 'string',
        'global_dimension_2_code' => 'string',
        'ic_partner_code' => 'string',
        'gen_posting_type' => 'string',
        'gen_bus_posting_group' => 'string',
        'gen_prod_posting_group' => 'string',
        'quantity' => 'float',
        'amount' => 'float',
        'debit_amount' => 'float',
        'credit_amount' => 'float',
        'additional_currency_amount' => 'float',
        'vat_amount' => 'float',
        'bal_account_type' => 'string',
        'bal_account_no' => 'string',
        'user_id' => 'string',
        'source_code' => 'string',
        'source_type' => 'string',
        'source_no' => 'string',
        'reason_code' => 'string',
        'reversed' => 'bool',
        'reversed_by_entry_no' => 'int',
        'reversed_entry_no' => 'int',
        'fa_entry_type' => 'string',
        'fa_entry_no' => 'int',
        'dimension_set_id' => 'int',
        'external_document_no' => 'string',
        'shortcut_dimension_3_code' => 'string',
        'shortcut_dimension_4_code' => 'string',
        'shortcut_dimension_5_code' => 'string',
        'shortcut_dimension_6_code' => 'string',
        'shortcut_dimension_7_code' => 'string',
        'shortcut_dimension_8_code' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'at_odata_etag' => null,
        'entry_no' => null,
        'posting_date' => null,
        'document_type' => null,
        'document_no' => null,
        'g_l_account_no' => null,
        'g_l_account_name' => null,
        'description' => null,
        'job_no' => null,
        'global_dimension_1_code' => null,
        'global_dimension_2_code' => null,
        'ic_partner_code' => null,
        'gen_posting_type' => null,
        'gen_bus_posting_group' => null,
        'gen_prod_posting_group' => null,
        'quantity' => null,
        'amount' => null,
        'debit_amount' => null,
        'credit_amount' => null,
        'additional_currency_amount' => null,
        'vat_amount' => null,
        'bal_account_type' => null,
        'bal_account_no' => null,
        'user_id' => null,
        'source_code' => null,
        'source_type' => null,
        'source_no' => null,
        'reason_code' => null,
        'reversed' => null,
        'reversed_by_entry_no' => null,
        'reversed_entry_no' => null,
        'fa_entry_type' => null,
        'fa_entry_no' => null,
        'dimension_set_id' => null,
        'external_document_no' => null,
        'shortcut_dimension_3_code' => null,
        'shortcut_dimension_4_code' => null,
        'shortcut_dimension_5_code' => null,
        'shortcut_dimension_6_code' => null,
        'shortcut_dimension_7_code' => null,
        'shortcut_dimension_8_code' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'at_odata_etag' => false,
        'entry_no' => false,
        'posting_date' => false,
        'document_type' => false,
        'document_no' => false,
        'g_l_account_no' => false,
        'g_l_account_name' => false,
        'description' => false,
        'job_no' => false,
        'global_dimension_1_code' => false,
        'global_dimension_2_code' => false,
        'ic_partner_code' => false,
        'gen_posting_type' => false,
        'gen_bus_posting_group' => false,
        'gen_prod_posting_group' => false,
        'quantity' => false,
        'amount' => false,
        'debit_amount' => false,
        'credit_amount' => false,
        'additional_currency_amount' => false,
        'vat_amount' => false,
        'bal_account_type' => false,
        'bal_account_no' => false,
        'user_id' => false,
        'source_code' => false,
        'source_type' => false,
        'source_no' => false,
        'reason_code' => false,
        'reversed' => false,
        'reversed_by_entry_no' => false,
        'reversed_entry_no' => false,
        'fa_entry_type' => false,
        'fa_entry_no' => false,
        'dimension_set_id' => false,
        'external_document_no' => false,
        'shortcut_dimension_3_code' => false,
        'shortcut_dimension_4_code' => false,
        'shortcut_dimension_5_code' => false,
        'shortcut_dimension_6_code' => false,
        'shortcut_dimension_7_code' => false,
        'shortcut_dimension_8_code' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'at_odata_etag' => '@odata.etag',
        'entry_no' => 'Entry_No',
        'posting_date' => 'Posting_Date',
        'document_type' => 'Document_Type',
        'document_no' => 'Document_No',
        'g_l_account_no' => 'G_L_Account_No',
        'g_l_account_name' => 'G_L_Account_Name',
        'description' => 'Description',
        'job_no' => 'Job_No',
        'global_dimension_1_code' => 'Global_Dimension_1_Code',
        'global_dimension_2_code' => 'Global_Dimension_2_Code',
        'ic_partner_code' => 'IC_Partner_Code',
        'gen_posting_type' => 'Gen_Posting_Type',
        'gen_bus_posting_group' => 'Gen_Bus_Posting_Group',
        'gen_prod_posting_group' => 'Gen_Prod_Posting_Group',
        'quantity' => 'Quantity',
        'amount' => 'Amount',
        'debit_amount' => 'Debit_Amount',
        'credit_amount' => 'Credit_Amount',
        'additional_currency_amount' => 'Additional_Currency_Amount',
        'vat_amount' => 'VAT_Amount',
        'bal_account_type' => 'Bal_Account_Type',
        'bal_account_no' => 'Bal_Account_No',
        'user_id' => 'User_ID',
        'source_code' => 'Source_Code',
        'source_type' => 'Source_Type',
        'source_no' => 'Source_No',
        'reason_code' => 'Reason_Code',
        'reversed' => 'Reversed',
        'reversed_by_entry_no' => 'Reversed_by_Entry_No',
        'reversed_entry_no' => 'Reversed_Entry_No',
        'fa_entry_type' => 'FA_Entry_Type',
        'fa_entry_no' => 'FA_Entry_No',
        'dimension_set_id' => 'Dimension_Set_ID',
        'external_document_no' => 'External_Document_No',
        'shortcut_dimension_3_code' => 'Shortcut_Dimension_3_Code',
        'shortcut_dimension_4_code' => 'Shortcut_Dimension_4_Code',
        'shortcut_dimension_5_code' => 'Shortcut_Dimension_5_Code',
        'shortcut_dimension_6_code' => 'Shortcut_Dimension_6_Code',
        'shortcut_dimension_7_code' => 'Shortcut_Dimension_7_Code',
        'shortcut_dimension_8_code' => 'Shortcut_Dimension_8_Code'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'at_odata_etag' => 'setAtOdataEtag',
        'entry_no' => 'setEntryNo',
        'posting_date' => 'setPostingDate',
        'document_type' => 'setDocumentType',
        'document_no' => 'setDocumentNo',
        'g_l_account_no' => 'setGLAccountNo',
        'g_l_account_name' => 'setGLAccountName',
        'description' => 'setDescription',
        'job_no' => 'setJobNo',
        'global_dimension_1_code' => 'setGlobalDimension1Code',
        'global_dimension_2_code' => 'setGlobalDimension2Code',
        'ic_partner_code' => 'setIcPartnerCode',
        'gen_posting_type' => 'setGenPostingType',
        'gen_bus_posting_group' => 'setGenBusPostingGroup',
        'gen_prod_posting_group' => 'setGenProdPostingGroup',
        'quantity' => 'setQuantity',
        'amount' => 'setAmount',
        'debit_amount' => 'setDebitAmount',
        'credit_amount' => 'setCreditAmount',
        'additional_currency_amount' => 'setAdditionalCurrencyAmount',
        'vat_amount' => 'setVatAmount',
        'bal_account_type' => 'setBalAccountType',
        'bal_account_no' => 'setBalAccountNo',
        'user_id' => 'setUserId',
        'source_code' => 'setSourceCode',
        'source_type' => 'setSourceType',
        'source_no' => 'setSourceNo',
        'reason_code' => 'setReasonCode',
        'reversed' => 'setReversed',
        'reversed_by_entry_no' => 'setReversedByEntryNo',
        'reversed_entry_no' => 'setReversedEntryNo',
        'fa_entry_type' => 'setFaEntryType',
        'fa_entry_no' => 'setFaEntryNo',
        'dimension_set_id' => 'setDimensionSetId',
        'external_document_no' => 'setExternalDocumentNo',
        'shortcut_dimension_3_code' => 'setShortcutDimension3Code',
        'shortcut_dimension_4_code' => 'setShortcutDimension4Code',
        'shortcut_dimension_5_code' => 'setShortcutDimension5Code',
        'shortcut_dimension_6_code' => 'setShortcutDimension6Code',
        'shortcut_dimension_7_code' => 'setShortcutDimension7Code',
        'shortcut_dimension_8_code' => 'setShortcutDimension8Code'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'at_odata_etag' => 'getAtOdataEtag',
        'entry_no' => 'getEntryNo',
        'posting_date' => 'getPostingDate',
        'document_type' => 'getDocumentType',
        'document_no' => 'getDocumentNo',
        'g_l_account_no' => 'getGLAccountNo',
        'g_l_account_name' => 'getGLAccountName',
        'description' => 'getDescription',
        'job_no' => 'getJobNo',
        'global_dimension_1_code' => 'getGlobalDimension1Code',
        'global_dimension_2_code' => 'getGlobalDimension2Code',
        'ic_partner_code' => 'getIcPartnerCode',
        'gen_posting_type' => 'getGenPostingType',
        'gen_bus_posting_group' => 'getGenBusPostingGroup',
        'gen_prod_posting_group' => 'getGenProdPostingGroup',
        'quantity' => 'getQuantity',
        'amount' => 'getAmount',
        'debit_amount' => 'getDebitAmount',
        'credit_amount' => 'getCreditAmount',
        'additional_currency_amount' => 'getAdditionalCurrencyAmount',
        'vat_amount' => 'getVatAmount',
        'bal_account_type' => 'getBalAccountType',
        'bal_account_no' => 'getBalAccountNo',
        'user_id' => 'getUserId',
        'source_code' => 'getSourceCode',
        'source_type' => 'getSourceType',
        'source_no' => 'getSourceNo',
        'reason_code' => 'getReasonCode',
        'reversed' => 'getReversed',
        'reversed_by_entry_no' => 'getReversedByEntryNo',
        'reversed_entry_no' => 'getReversedEntryNo',
        'fa_entry_type' => 'getFaEntryType',
        'fa_entry_no' => 'getFaEntryNo',
        'dimension_set_id' => 'getDimensionSetId',
        'external_document_no' => 'getExternalDocumentNo',
        'shortcut_dimension_3_code' => 'getShortcutDimension3Code',
        'shortcut_dimension_4_code' => 'getShortcutDimension4Code',
        'shortcut_dimension_5_code' => 'getShortcutDimension5Code',
        'shortcut_dimension_6_code' => 'getShortcutDimension6Code',
        'shortcut_dimension_7_code' => 'getShortcutDimension7Code',
        'shortcut_dimension_8_code' => 'getShortcutDimension8Code'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const DOCUMENT_TYPE_SPACE_1 = ' ';
    public const DOCUMENT_TYPE_PAYMENT = 'Payment';
    public const DOCUMENT_TYPE_INVOICE = 'Invoice';
    public const DOCUMENT_TYPE_CREDIT_MEMO = 'Credit Memo';
    public const DOCUMENT_TYPE_FINANCE_CHARGE_MEMO = 'Finance Charge Memo';
    public const DOCUMENT_TYPE_REMINDER = 'Reminder';
    public const DOCUMENT_TYPE_REFUND = 'Refund';
    public const GEN_POSTING_TYPE_SPACE_1 = ' ';
    public const GEN_POSTING_TYPE_PURCHASE = 'Purchase';
    public const GEN_POSTING_TYPE_SALE = 'Sale';
    public const GEN_POSTING_TYPE_SETTLEMENT = 'Settlement';
    public const BAL_ACCOUNT_TYPE_G_L_ACCOUNT = 'G/L Account';
    public const BAL_ACCOUNT_TYPE_CUSTOMER = 'Customer';
    public const BAL_ACCOUNT_TYPE_VENDOR = 'Vendor';
    public const BAL_ACCOUNT_TYPE_BANK_ACCOUNT = 'Bank Account';
    public const BAL_ACCOUNT_TYPE_FIXED_ASSET = 'Fixed Asset';
    public const BAL_ACCOUNT_TYPE_IC_PARTNER = 'IC Partner';
    public const BAL_ACCOUNT_TYPE_EMPLOYEE = 'Employee';
    public const SOURCE_TYPE_SPACE_1 = ' ';
    public const SOURCE_TYPE_CUSTOMER = 'Customer';
    public const SOURCE_TYPE_VENDOR = 'Vendor';
    public const SOURCE_TYPE_BANK_ACCOUNT = 'Bank Account';
    public const SOURCE_TYPE_FIXED_ASSET = 'Fixed Asset';
    public const SOURCE_TYPE_IC_PARTNER = 'IC Partner';
    public const SOURCE_TYPE_EMPLOYEE = 'Employee';
    public const FA_ENTRY_TYPE_SPACE_1 = ' ';
    public const FA_ENTRY_TYPE_FIXED_ASSET = 'Fixed Asset';
    public const FA_ENTRY_TYPE_MAINTENANCE = 'Maintenance';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getDocumentTypeAllowableValues()
    {
        return [
            self::DOCUMENT_TYPE_SPACE_1,
            self::DOCUMENT_TYPE_PAYMENT,
            self::DOCUMENT_TYPE_INVOICE,
            self::DOCUMENT_TYPE_CREDIT_MEMO,
            self::DOCUMENT_TYPE_FINANCE_CHARGE_MEMO,
            self::DOCUMENT_TYPE_REMINDER,
            self::DOCUMENT_TYPE_REFUND,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getGenPostingTypeAllowableValues()
    {
        return [
            self::GEN_POSTING_TYPE_SPACE_1,
            self::GEN_POSTING_TYPE_PURCHASE,
            self::GEN_POSTING_TYPE_SALE,
            self::GEN_POSTING_TYPE_SETTLEMENT,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getBalAccountTypeAllowableValues()
    {
        return [
            self::BAL_ACCOUNT_TYPE_G_L_ACCOUNT,
            self::BAL_ACCOUNT_TYPE_CUSTOMER,
            self::BAL_ACCOUNT_TYPE_VENDOR,
            self::BAL_ACCOUNT_TYPE_BANK_ACCOUNT,
            self::BAL_ACCOUNT_TYPE_FIXED_ASSET,
            self::BAL_ACCOUNT_TYPE_IC_PARTNER,
            self::BAL_ACCOUNT_TYPE_EMPLOYEE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSourceTypeAllowableValues()
    {
        return [
            self::SOURCE_TYPE_SPACE_1,
            self::SOURCE_TYPE_CUSTOMER,
            self::SOURCE_TYPE_VENDOR,
            self::SOURCE_TYPE_BANK_ACCOUNT,
            self::SOURCE_TYPE_FIXED_ASSET,
            self::SOURCE_TYPE_IC_PARTNER,
            self::SOURCE_TYPE_EMPLOYEE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getFaEntryTypeAllowableValues()
    {
        return [
            self::FA_ENTRY_TYPE_SPACE_1,
            self::FA_ENTRY_TYPE_FIXED_ASSET,
            self::FA_ENTRY_TYPE_MAINTENANCE,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('at_odata_etag', $data ?? [], null);
        $this->setIfExists('entry_no', $data ?? [], null);
        $this->setIfExists('posting_date', $data ?? [], null);
        $this->setIfExists('document_type', $data ?? [], null);
        $this->setIfExists('document_no', $data ?? [], null);
        $this->setIfExists('g_l_account_no', $data ?? [], null);
        $this->setIfExists('g_l_account_name', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('job_no', $data ?? [], null);
        $this->setIfExists('global_dimension_1_code', $data ?? [], null);
        $this->setIfExists('global_dimension_2_code', $data ?? [], null);
        $this->setIfExists('ic_partner_code', $data ?? [], null);
        $this->setIfExists('gen_posting_type', $data ?? [], null);
        $this->setIfExists('gen_bus_posting_group', $data ?? [], null);
        $this->setIfExists('gen_prod_posting_group', $data ?? [], null);
        $this->setIfExists('quantity', $data ?? [], null);
        $this->setIfExists('amount', $data ?? [], null);
        $this->setIfExists('debit_amount', $data ?? [], null);
        $this->setIfExists('credit_amount', $data ?? [], null);
        $this->setIfExists('additional_currency_amount', $data ?? [], null);
        $this->setIfExists('vat_amount', $data ?? [], null);
        $this->setIfExists('bal_account_type', $data ?? [], null);
        $this->setIfExists('bal_account_no', $data ?? [], null);
        $this->setIfExists('user_id', $data ?? [], null);
        $this->setIfExists('source_code', $data ?? [], null);
        $this->setIfExists('source_type', $data ?? [], null);
        $this->setIfExists('source_no', $data ?? [], null);
        $this->setIfExists('reason_code', $data ?? [], null);
        $this->setIfExists('reversed', $data ?? [], null);
        $this->setIfExists('reversed_by_entry_no', $data ?? [], null);
        $this->setIfExists('reversed_entry_no', $data ?? [], null);
        $this->setIfExists('fa_entry_type', $data ?? [], null);
        $this->setIfExists('fa_entry_no', $data ?? [], null);
        $this->setIfExists('dimension_set_id', $data ?? [], null);
        $this->setIfExists('external_document_no', $data ?? [], null);
        $this->setIfExists('shortcut_dimension_3_code', $data ?? [], null);
        $this->setIfExists('shortcut_dimension_4_code', $data ?? [], null);
        $this->setIfExists('shortcut_dimension_5_code', $data ?? [], null);
        $this->setIfExists('shortcut_dimension_6_code', $data ?? [], null);
        $this->setIfExists('shortcut_dimension_7_code', $data ?? [], null);
        $this->setIfExists('shortcut_dimension_8_code', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getDocumentTypeAllowableValues();
        if (!is_null($this->container['document_type']) && !in_array($this->container['document_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'document_type', must be one of '%s'",
                $this->container['document_type'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getGenPostingTypeAllowableValues();
        if (!is_null($this->container['gen_posting_type']) && !in_array($this->container['gen_posting_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'gen_posting_type', must be one of '%s'",
                $this->container['gen_posting_type'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getBalAccountTypeAllowableValues();
        if (!is_null($this->container['bal_account_type']) && !in_array($this->container['bal_account_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'bal_account_type', must be one of '%s'",
                $this->container['bal_account_type'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getSourceTypeAllowableValues();
        if (!is_null($this->container['source_type']) && !in_array($this->container['source_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'source_type', must be one of '%s'",
                $this->container['source_type'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getFaEntryTypeAllowableValues();
        if (!is_null($this->container['fa_entry_type']) && !in_array($this->container['fa_entry_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'fa_entry_type', must be one of '%s'",
                $this->container['fa_entry_type'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets at_odata_etag
     *
     * @return string|null
     */
    public function getAtOdataEtag()
    {
        return $this->container['at_odata_etag'];
    }

    /**
     * Sets at_odata_etag
     *
     * @param string|null $at_odata_etag If-Match header for updates
     *
     * @return self
     */
    public function setAtOdataEtag($at_odata_etag)
    {
        if (is_null($at_odata_etag)) {
            throw new \InvalidArgumentException('non-nullable at_odata_etag cannot be null');
        }
        $this->container['at_odata_etag'] = $at_odata_etag;

        return $this;
    }

    /**
     * Gets entry_no
     *
     * @return int|null
     */
    public function getEntryNo()
    {
        return $this->container['entry_no'];
    }

    /**
     * Sets entry_no
     *
     * @param int|null $entry_no entry_no
     *
     * @return self
     */
    public function setEntryNo($entry_no)
    {
        if (is_null($entry_no)) {
            throw new \InvalidArgumentException('non-nullable entry_no cannot be null');
        }
        $this->container['entry_no'] = $entry_no;

        return $this;
    }

    /**
     * Gets posting_date
     *
     * @return string|null
     */
    public function getPostingDate()
    {
        return $this->container['posting_date'];
    }

    /**
     * Sets posting_date
     *
     * @param string|null $posting_date posting_date
     *
     * @return self
     */
    public function setPostingDate($posting_date)
    {
        if (is_null($posting_date)) {
            throw new \InvalidArgumentException('non-nullable posting_date cannot be null');
        }
        $this->container['posting_date'] = $posting_date;

        return $this;
    }

    /**
     * Gets document_type
     *
     * @return string|null
     */
    public function getDocumentType()
    {
        return $this->container['document_type'];
    }

    /**
     * Sets document_type
     *
     * @param string|null $document_type document_type
     *
     * @return self
     */
    public function setDocumentType($document_type)
    {
        if (is_null($document_type)) {
            throw new \InvalidArgumentException('non-nullable document_type cannot be null');
        }
        $allowedValues = $this->getDocumentTypeAllowableValues();
        if (!in_array($document_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'document_type', must be one of '%s'",
                    $document_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['document_type'] = $document_type;

        return $this;
    }

    /**
     * Gets document_no
     *
     * @return string|null
     */
    public function getDocumentNo()
    {
        return $this->container['document_no'];
    }

    /**
     * Sets document_no
     *
     * @param string|null $document_no document_no
     *
     * @return self
     */
    public function setDocumentNo($document_no)
    {
        if (is_null($document_no)) {
            throw new \InvalidArgumentException('non-nullable document_no cannot be null');
        }
        $this->container['document_no'] = $document_no;

        return $this;
    }

    /**
     * Gets g_l_account_no
     *
     * @return string|null
     */
    public function getGLAccountNo()
    {
        return $this->container['g_l_account_no'];
    }

    /**
     * Sets g_l_account_no
     *
     * @param string|null $g_l_account_no g_l_account_no
     *
     * @return self
     */
    public function setGLAccountNo($g_l_account_no)
    {
        if (is_null($g_l_account_no)) {
            throw new \InvalidArgumentException('non-nullable g_l_account_no cannot be null');
        }
        $this->container['g_l_account_no'] = $g_l_account_no;

        return $this;
    }

    /**
     * Gets g_l_account_name
     *
     * @return string|null
     */
    public function getGLAccountName()
    {
        return $this->container['g_l_account_name'];
    }

    /**
     * Sets g_l_account_name
     *
     * @param string|null $g_l_account_name g_l_account_name
     *
     * @return self
     */
    public function setGLAccountName($g_l_account_name)
    {
        if (is_null($g_l_account_name)) {
            throw new \InvalidArgumentException('non-nullable g_l_account_name cannot be null');
        }
        $this->container['g_l_account_name'] = $g_l_account_name;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets job_no
     *
     * @return string|null
     */
    public function getJobNo()
    {
        return $this->container['job_no'];
    }

    /**
     * Sets job_no
     *
     * @param string|null $job_no job_no
     *
     * @return self
     */
    public function setJobNo($job_no)
    {
        if (is_null($job_no)) {
            throw new \InvalidArgumentException('non-nullable job_no cannot be null');
        }
        $this->container['job_no'] = $job_no;

        return $this;
    }

    /**
     * Gets global_dimension_1_code
     *
     * @return string|null
     */
    public function getGlobalDimension1Code()
    {
        return $this->container['global_dimension_1_code'];
    }

    /**
     * Sets global_dimension_1_code
     *
     * @param string|null $global_dimension_1_code global_dimension_1_code
     *
     * @return self
     */
    public function setGlobalDimension1Code($global_dimension_1_code)
    {
        if (is_null($global_dimension_1_code)) {
            throw new \InvalidArgumentException('non-nullable global_dimension_1_code cannot be null');
        }
        $this->container['global_dimension_1_code'] = $global_dimension_1_code;

        return $this;
    }

    /**
     * Gets global_dimension_2_code
     *
     * @return string|null
     */
    public function getGlobalDimension2Code()
    {
        return $this->container['global_dimension_2_code'];
    }

    /**
     * Sets global_dimension_2_code
     *
     * @param string|null $global_dimension_2_code global_dimension_2_code
     *
     * @return self
     */
    public function setGlobalDimension2Code($global_dimension_2_code)
    {
        if (is_null($global_dimension_2_code)) {
            throw new \InvalidArgumentException('non-nullable global_dimension_2_code cannot be null');
        }
        $this->container['global_dimension_2_code'] = $global_dimension_2_code;

        return $this;
    }

    /**
     * Gets ic_partner_code
     *
     * @return string|null
     */
    public function getIcPartnerCode()
    {
        return $this->container['ic_partner_code'];
    }

    /**
     * Sets ic_partner_code
     *
     * @param string|null $ic_partner_code ic_partner_code
     *
     * @return self
     */
    public function setIcPartnerCode($ic_partner_code)
    {
        if (is_null($ic_partner_code)) {
            throw new \InvalidArgumentException('non-nullable ic_partner_code cannot be null');
        }
        $this->container['ic_partner_code'] = $ic_partner_code;

        return $this;
    }

    /**
     * Gets gen_posting_type
     *
     * @return string|null
     */
    public function getGenPostingType()
    {
        return $this->container['gen_posting_type'];
    }

    /**
     * Sets gen_posting_type
     *
     * @param string|null $gen_posting_type gen_posting_type
     *
     * @return self
     */
    public function setGenPostingType($gen_posting_type)
    {
        if (is_null($gen_posting_type)) {
            throw new \InvalidArgumentException('non-nullable gen_posting_type cannot be null');
        }
        $allowedValues = $this->getGenPostingTypeAllowableValues();
        if (!in_array($gen_posting_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'gen_posting_type', must be one of '%s'",
                    $gen_posting_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['gen_posting_type'] = $gen_posting_type;

        return $this;
    }

    /**
     * Gets gen_bus_posting_group
     *
     * @return string|null
     */
    public function getGenBusPostingGroup()
    {
        return $this->container['gen_bus_posting_group'];
    }

    /**
     * Sets gen_bus_posting_group
     *
     * @param string|null $gen_bus_posting_group gen_bus_posting_group
     *
     * @return self
     */
    public function setGenBusPostingGroup($gen_bus_posting_group)
    {
        if (is_null($gen_bus_posting_group)) {
            throw new \InvalidArgumentException('non-nullable gen_bus_posting_group cannot be null');
        }
        $this->container['gen_bus_posting_group'] = $gen_bus_posting_group;

        return $this;
    }

    /**
     * Gets gen_prod_posting_group
     *
     * @return string|null
     */
    public function getGenProdPostingGroup()
    {
        return $this->container['gen_prod_posting_group'];
    }

    /**
     * Sets gen_prod_posting_group
     *
     * @param string|null $gen_prod_posting_group gen_prod_posting_group
     *
     * @return self
     */
    public function setGenProdPostingGroup($gen_prod_posting_group)
    {
        if (is_null($gen_prod_posting_group)) {
            throw new \InvalidArgumentException('non-nullable gen_prod_posting_group cannot be null');
        }
        $this->container['gen_prod_posting_group'] = $gen_prod_posting_group;

        return $this;
    }

    /**
     * Gets quantity
     *
     * @return float|null
     */
    public function getQuantity()
    {
        return $this->container['quantity'];
    }

    /**
     * Sets quantity
     *
     * @param float|null $quantity quantity
     *
     * @return self
     */
    public function setQuantity($quantity)
    {
        if (is_null($quantity)) {
            throw new \InvalidArgumentException('non-nullable quantity cannot be null');
        }
        $this->container['quantity'] = $quantity;

        return $this;
    }

    /**
     * Gets amount
     *
     * @return float|null
     */
    public function getAmount()
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param float|null $amount amount
     *
     * @return self
     */
    public function setAmount($amount)
    {
        if (is_null($amount)) {
            throw new \InvalidArgumentException('non-nullable amount cannot be null');
        }
        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets debit_amount
     *
     * @return float|null
     */
    public function getDebitAmount()
    {
        return $this->container['debit_amount'];
    }

    /**
     * Sets debit_amount
     *
     * @param float|null $debit_amount debit_amount
     *
     * @return self
     */
    public function setDebitAmount($debit_amount)
    {
        if (is_null($debit_amount)) {
            throw new \InvalidArgumentException('non-nullable debit_amount cannot be null');
        }
        $this->container['debit_amount'] = $debit_amount;

        return $this;
    }

    /**
     * Gets credit_amount
     *
     * @return float|null
     */
    public function getCreditAmount()
    {
        return $this->container['credit_amount'];
    }

    /**
     * Sets credit_amount
     *
     * @param float|null $credit_amount credit_amount
     *
     * @return self
     */
    public function setCreditAmount($credit_amount)
    {
        if (is_null($credit_amount)) {
            throw new \InvalidArgumentException('non-nullable credit_amount cannot be null');
        }
        $this->container['credit_amount'] = $credit_amount;

        return $this;
    }

    /**
     * Gets additional_currency_amount
     *
     * @return float|null
     */
    public function getAdditionalCurrencyAmount()
    {
        return $this->container['additional_currency_amount'];
    }

    /**
     * Sets additional_currency_amount
     *
     * @param float|null $additional_currency_amount additional_currency_amount
     *
     * @return self
     */
    public function setAdditionalCurrencyAmount($additional_currency_amount)
    {
        if (is_null($additional_currency_amount)) {
            throw new \InvalidArgumentException('non-nullable additional_currency_amount cannot be null');
        }
        $this->container['additional_currency_amount'] = $additional_currency_amount;

        return $this;
    }

    /**
     * Gets vat_amount
     *
     * @return float|null
     */
    public function getVatAmount()
    {
        return $this->container['vat_amount'];
    }

    /**
     * Sets vat_amount
     *
     * @param float|null $vat_amount vat_amount
     *
     * @return self
     */
    public function setVatAmount($vat_amount)
    {
        if (is_null($vat_amount)) {
            throw new \InvalidArgumentException('non-nullable vat_amount cannot be null');
        }
        $this->container['vat_amount'] = $vat_amount;

        return $this;
    }

    /**
     * Gets bal_account_type
     *
     * @return string|null
     */
    public function getBalAccountType()
    {
        return $this->container['bal_account_type'];
    }

    /**
     * Sets bal_account_type
     *
     * @param string|null $bal_account_type bal_account_type
     *
     * @return self
     */
    public function setBalAccountType($bal_account_type)
    {
        if (is_null($bal_account_type)) {
            throw new \InvalidArgumentException('non-nullable bal_account_type cannot be null');
        }
        $allowedValues = $this->getBalAccountTypeAllowableValues();
        if (!in_array($bal_account_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'bal_account_type', must be one of '%s'",
                    $bal_account_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['bal_account_type'] = $bal_account_type;

        return $this;
    }

    /**
     * Gets bal_account_no
     *
     * @return string|null
     */
    public function getBalAccountNo()
    {
        return $this->container['bal_account_no'];
    }

    /**
     * Sets bal_account_no
     *
     * @param string|null $bal_account_no bal_account_no
     *
     * @return self
     */
    public function setBalAccountNo($bal_account_no)
    {
        if (is_null($bal_account_no)) {
            throw new \InvalidArgumentException('non-nullable bal_account_no cannot be null');
        }
        $this->container['bal_account_no'] = $bal_account_no;

        return $this;
    }

    /**
     * Gets user_id
     *
     * @return string|null
     */
    public function getUserId()
    {
        return $this->container['user_id'];
    }

    /**
     * Sets user_id
     *
     * @param string|null $user_id user_id
     *
     * @return self
     */
    public function setUserId($user_id)
    {
        if (is_null($user_id)) {
            throw new \InvalidArgumentException('non-nullable user_id cannot be null');
        }
        $this->container['user_id'] = $user_id;

        return $this;
    }

    /**
     * Gets source_code
     *
     * @return string|null
     */
    public function getSourceCode()
    {
        return $this->container['source_code'];
    }

    /**
     * Sets source_code
     *
     * @param string|null $source_code source_code
     *
     * @return self
     */
    public function setSourceCode($source_code)
    {
        if (is_null($source_code)) {
            throw new \InvalidArgumentException('non-nullable source_code cannot be null');
        }
        $this->container['source_code'] = $source_code;

        return $this;
    }

    /**
     * Gets source_type
     *
     * @return string|null
     */
    public function getSourceType()
    {
        return $this->container['source_type'];
    }

    /**
     * Sets source_type
     *
     * @param string|null $source_type source_type
     *
     * @return self
     */
    public function setSourceType($source_type)
    {
        if (is_null($source_type)) {
            throw new \InvalidArgumentException('non-nullable source_type cannot be null');
        }
        $allowedValues = $this->getSourceTypeAllowableValues();
        if (!in_array($source_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'source_type', must be one of '%s'",
                    $source_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['source_type'] = $source_type;

        return $this;
    }

    /**
     * Gets source_no
     *
     * @return string|null
     */
    public function getSourceNo()
    {
        return $this->container['source_no'];
    }

    /**
     * Sets source_no
     *
     * @param string|null $source_no source_no
     *
     * @return self
     */
    public function setSourceNo($source_no)
    {
        if (is_null($source_no)) {
            throw new \InvalidArgumentException('non-nullable source_no cannot be null');
        }
        $this->container['source_no'] = $source_no;

        return $this;
    }

    /**
     * Gets reason_code
     *
     * @return string|null
     */
    public function getReasonCode()
    {
        return $this->container['reason_code'];
    }

    /**
     * Sets reason_code
     *
     * @param string|null $reason_code reason_code
     *
     * @return self
     */
    public function setReasonCode($reason_code)
    {
        if (is_null($reason_code)) {
            throw new \InvalidArgumentException('non-nullable reason_code cannot be null');
        }
        $this->container['reason_code'] = $reason_code;

        return $this;
    }

    /**
     * Gets reversed
     *
     * @return bool|null
     */
    public function getReversed()
    {
        return $this->container['reversed'];
    }

    /**
     * Sets reversed
     *
     * @param bool|null $reversed reversed
     *
     * @return self
     */
    public function setReversed($reversed)
    {
        if (is_null($reversed)) {
            throw new \InvalidArgumentException('non-nullable reversed cannot be null');
        }
        $this->container['reversed'] = $reversed;

        return $this;
    }

    /**
     * Gets reversed_by_entry_no
     *
     * @return int|null
     */
    public function getReversedByEntryNo()
    {
        return $this->container['reversed_by_entry_no'];
    }

    /**
     * Sets reversed_by_entry_no
     *
     * @param int|null $reversed_by_entry_no reversed_by_entry_no
     *
     * @return self
     */
    public function setReversedByEntryNo($reversed_by_entry_no)
    {
        if (is_null($reversed_by_entry_no)) {
            throw new \InvalidArgumentException('non-nullable reversed_by_entry_no cannot be null');
        }
        $this->container['reversed_by_entry_no'] = $reversed_by_entry_no;

        return $this;
    }

    /**
     * Gets reversed_entry_no
     *
     * @return int|null
     */
    public function getReversedEntryNo()
    {
        return $this->container['reversed_entry_no'];
    }

    /**
     * Sets reversed_entry_no
     *
     * @param int|null $reversed_entry_no reversed_entry_no
     *
     * @return self
     */
    public function setReversedEntryNo($reversed_entry_no)
    {
        if (is_null($reversed_entry_no)) {
            throw new \InvalidArgumentException('non-nullable reversed_entry_no cannot be null');
        }
        $this->container['reversed_entry_no'] = $reversed_entry_no;

        return $this;
    }

    /**
     * Gets fa_entry_type
     *
     * @return string|null
     */
    public function getFaEntryType()
    {
        return $this->container['fa_entry_type'];
    }

    /**
     * Sets fa_entry_type
     *
     * @param string|null $fa_entry_type fa_entry_type
     *
     * @return self
     */
    public function setFaEntryType($fa_entry_type)
    {
        if (is_null($fa_entry_type)) {
            throw new \InvalidArgumentException('non-nullable fa_entry_type cannot be null');
        }
        $allowedValues = $this->getFaEntryTypeAllowableValues();
        if (!in_array($fa_entry_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'fa_entry_type', must be one of '%s'",
                    $fa_entry_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['fa_entry_type'] = $fa_entry_type;

        return $this;
    }

    /**
     * Gets fa_entry_no
     *
     * @return int|null
     */
    public function getFaEntryNo()
    {
        return $this->container['fa_entry_no'];
    }

    /**
     * Sets fa_entry_no
     *
     * @param int|null $fa_entry_no fa_entry_no
     *
     * @return self
     */
    public function setFaEntryNo($fa_entry_no)
    {
        if (is_null($fa_entry_no)) {
            throw new \InvalidArgumentException('non-nullable fa_entry_no cannot be null');
        }
        $this->container['fa_entry_no'] = $fa_entry_no;

        return $this;
    }

    /**
     * Gets dimension_set_id
     *
     * @return int|null
     */
    public function getDimensionSetId()
    {
        return $this->container['dimension_set_id'];
    }

    /**
     * Sets dimension_set_id
     *
     * @param int|null $dimension_set_id dimension_set_id
     *
     * @return self
     */
    public function setDimensionSetId($dimension_set_id)
    {
        if (is_null($dimension_set_id)) {
            throw new \InvalidArgumentException('non-nullable dimension_set_id cannot be null');
        }
        $this->container['dimension_set_id'] = $dimension_set_id;

        return $this;
    }

    /**
     * Gets external_document_no
     *
     * @return string|null
     */
    public function getExternalDocumentNo()
    {
        return $this->container['external_document_no'];
    }

    /**
     * Sets external_document_no
     *
     * @param string|null $external_document_no external_document_no
     *
     * @return self
     */
    public function setExternalDocumentNo($external_document_no)
    {
        if (is_null($external_document_no)) {
            throw new \InvalidArgumentException('non-nullable external_document_no cannot be null');
        }
        $this->container['external_document_no'] = $external_document_no;

        return $this;
    }

    /**
     * Gets shortcut_dimension_3_code
     *
     * @return string|null
     */
    public function getShortcutDimension3Code()
    {
        return $this->container['shortcut_dimension_3_code'];
    }

    /**
     * Sets shortcut_dimension_3_code
     *
     * @param string|null $shortcut_dimension_3_code shortcut_dimension_3_code
     *
     * @return self
     */
    public function setShortcutDimension3Code($shortcut_dimension_3_code)
    {
        if (is_null($shortcut_dimension_3_code)) {
            throw new \InvalidArgumentException('non-nullable shortcut_dimension_3_code cannot be null');
        }
        $this->container['shortcut_dimension_3_code'] = $shortcut_dimension_3_code;

        return $this;
    }

    /**
     * Gets shortcut_dimension_4_code
     *
     * @return string|null
     */
    public function getShortcutDimension4Code()
    {
        return $this->container['shortcut_dimension_4_code'];
    }

    /**
     * Sets shortcut_dimension_4_code
     *
     * @param string|null $shortcut_dimension_4_code shortcut_dimension_4_code
     *
     * @return self
     */
    public function setShortcutDimension4Code($shortcut_dimension_4_code)
    {
        if (is_null($shortcut_dimension_4_code)) {
            throw new \InvalidArgumentException('non-nullable shortcut_dimension_4_code cannot be null');
        }
        $this->container['shortcut_dimension_4_code'] = $shortcut_dimension_4_code;

        return $this;
    }

    /**
     * Gets shortcut_dimension_5_code
     *
     * @return string|null
     */
    public function getShortcutDimension5Code()
    {
        return $this->container['shortcut_dimension_5_code'];
    }

    /**
     * Sets shortcut_dimension_5_code
     *
     * @param string|null $shortcut_dimension_5_code shortcut_dimension_5_code
     *
     * @return self
     */
    public function setShortcutDimension5Code($shortcut_dimension_5_code)
    {
        if (is_null($shortcut_dimension_5_code)) {
            throw new \InvalidArgumentException('non-nullable shortcut_dimension_5_code cannot be null');
        }
        $this->container['shortcut_dimension_5_code'] = $shortcut_dimension_5_code;

        return $this;
    }

    /**
     * Gets shortcut_dimension_6_code
     *
     * @return string|null
     */
    public function getShortcutDimension6Code()
    {
        return $this->container['shortcut_dimension_6_code'];
    }

    /**
     * Sets shortcut_dimension_6_code
     *
     * @param string|null $shortcut_dimension_6_code shortcut_dimension_6_code
     *
     * @return self
     */
    public function setShortcutDimension6Code($shortcut_dimension_6_code)
    {
        if (is_null($shortcut_dimension_6_code)) {
            throw new \InvalidArgumentException('non-nullable shortcut_dimension_6_code cannot be null');
        }
        $this->container['shortcut_dimension_6_code'] = $shortcut_dimension_6_code;

        return $this;
    }

    /**
     * Gets shortcut_dimension_7_code
     *
     * @return string|null
     */
    public function getShortcutDimension7Code()
    {
        return $this->container['shortcut_dimension_7_code'];
    }

    /**
     * Sets shortcut_dimension_7_code
     *
     * @param string|null $shortcut_dimension_7_code shortcut_dimension_7_code
     *
     * @return self
     */
    public function setShortcutDimension7Code($shortcut_dimension_7_code)
    {
        if (is_null($shortcut_dimension_7_code)) {
            throw new \InvalidArgumentException('non-nullable shortcut_dimension_7_code cannot be null');
        }
        $this->container['shortcut_dimension_7_code'] = $shortcut_dimension_7_code;

        return $this;
    }

    /**
     * Gets shortcut_dimension_8_code
     *
     * @return string|null
     */
    public function getShortcutDimension8Code()
    {
        return $this->container['shortcut_dimension_8_code'];
    }

    /**
     * Sets shortcut_dimension_8_code
     *
     * @param string|null $shortcut_dimension_8_code shortcut_dimension_8_code
     *
     * @return self
     */
    public function setShortcutDimension8Code($shortcut_dimension_8_code)
    {
        if (is_null($shortcut_dimension_8_code)) {
            throw new \InvalidArgumentException('non-nullable shortcut_dimension_8_code cannot be null');
        }
        $this->container['shortcut_dimension_8_code'] = $shortcut_dimension_8_code;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return (string)json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


