<?php
/**
 * SpyTemplateLineModelAttributes
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Spy\MsbcRestClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Microsoft Business Center API
 *
 * The Microsoft Business Center API is a RESTful API that provides an interface to the Microsoft Business Center service.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Spy\MsbcRestClient\Model;

/**
 * SpyTemplateLineModelAttributes Class Doc Comment
 *
 * @category Class
 * @package  Spy\MsbcRestClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SpyTemplateLineModelAttributes
{
    public string $strAtOdataEtag = 'at_odata_etag';
    public string $strTemplate = 'template';
    public string $strLineNo = 'line_no';
    public string $strType = 'type';
    public string $strFieldId = 'field_id';
    public string $strFieldName = 'field_name';
    public string $strTableId = 'table_id';
    public string $strTableName = 'table_name';
    public string $strTemplateCode = 'template_code';
    public string $strTemplateDescription = 'template_description';
    public string $strDefaultValue = 'default_value';
}

