<?php
/**
 * SpyVatPostingSetupResponseModelAttributes
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Spy\MsbcRestClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Microsoft Business Center API
 *
 * The Microsoft Business Center API is a RESTful API that provides an interface to the Microsoft Business Center service.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Spy\MsbcRestClient\Model;

/**
 * SpyVatPostingSetupResponseModelAttributes Class Doc Comment
 *
 * @category Class
 * @package  Spy\MsbcRestClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SpyVatPostingSetupResponseModelAttributes
{
    public string $strAtOdataContext = 'at_odata_context';
    public string $strAtOdataEtag = 'at_odata_etag';
    public string $strVatBusPostingGroup = 'vat_bus_posting_group';
    public string $strVatProdPostingGroup = 'vat_prod_posting_group';
    public string $strDescription = 'description';
    public string $strBlocked = 'blocked';
    public string $strVatIdentifier = 'vat_identifier';
    public string $strVatPercent = 'vat_percent';
    public string $strVatCalculationType = 'vat_calculation_type';
    public string $strUnrealizedVatType = 'unrealized_vat_type';
    public string $strAdjustForPaymentDiscount = 'adjust_for_payment_discount';
    public string $strSalesVatAccount = 'sales_vat_account';
    public string $strSalesVatUnrealAccount = 'sales_vat_unreal_account';
    public string $strPurchaseVatAccount = 'purchase_vat_account';
    public string $strPurchVatUnrealAccount = 'purch_vat_unreal_account';
    public string $strReverseChrgVatAcc = 'reverse_chrg_vat_acc';
    public string $strReverseChrgVatUnrealAcc = 'reverse_chrg_vat_unreal_acc';
    public string $strVatClauseCode = 'vat_clause_code';
    public string $strEuService = 'eu_service';
    public string $strCertificateOfSupplyRequired = 'certificate_of_supply_required';
    public string $strTaxCategory = 'tax_category';
}

