<?php
/**
 * SpyFieldsResponseTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Spy\MsbcRestClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Microsoft Business Center API
 *
 * The Microsoft Business Center API is a RESTful API that provides an interface to the Microsoft Business Center service.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Spy\MsbcRestClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * SpyFieldsResponseTest Class Doc Comment
 *
 * @category    Class
 * @description SpyFieldsResponse
 * @package     Spy\MsbcRestClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SpyFieldsResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SpyFieldsResponse"
     */
    public function testSpyFieldsResponse()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "at_odata_context"
     */
    public function testPropertyAtOdataContext()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "at_odata_etag"
     */
    public function testPropertyAtOdataEtag()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "table_no"
     */
    public function testPropertyTableNo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "field_no"
     */
    public function testPropertyFieldNo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "table_name"
     */
    public function testPropertyTableName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "field_name"
     */
    public function testPropertyFieldName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
