openapi: "3.0.0"
info:
  version: "1.0.0"
  title: "Microsoft Business Center API"
  description: |
    The Microsoft Business Center API is a RESTful API that provides an interface to the Microsoft Business Center service.

servers:
  - url: https://api.businesscentral.dynamics.com/v2.0/{tenantID}/{environment}/ODataV4/Company('{companyName}')
    description: URL for regular access to the Microsoft Business Center API.
    variables:
      tenantID:
        description: Tenant ID
        default: "{{ tenant_id }}"
      companyName:
        description: Company name
        default: "CRONUS%20Danmark%20A%2FS"
      environment:
        description: "Environment: Production or Sandbox"
        default: Production
        enum:
          - Production
          - Sandbox

tags:
  - name: Authenticate
    description: |
      Authentication operations for Microsoft Business Center API.

paths:
  /token:
    description: |
      This endpoint is used to obtain an access token for the Microsoft Business Center API.
      The access token is valid for one hour.
    post:
      operationId: Authenticate
      security: []
      tags: [Authenticate]
      servers:
        - url: https://login.microsoftonline.com/{tenantID}/oauth2/v2.0
          variables:
            tenantID:
              description: Tenant ID
              default: "{{ tenant_id }}"
      requestBody:
        $ref: '#/components/requestBodies/Authenticate'
      responses:
        '200':
          $ref: '#/components/responses/Authorized'
        '401':
          $ref: '#/components/responses/Unauthorized'
        default:
          $ref: '#/components/responses/Default'

security:
  - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

  requestBodies:
    Authenticate:
      description: |
        This request body is used to obtain an access token for the Microsoft Business Center API.
        The access token is valid for one hour.
      required: true
      content:
        application/x-www-form-urlencoded:
          schema:
            $ref: '#/components/schemas/Authenticate'

  responses:
    Authorized:
      description: |
        This response body is used to obtain an access token for the Microsoft Business Center API.
        The access token is valid for one hour.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AuthenticateResponse'
    Unauthorized:
      description: |
        Response body for when the authentication fails.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Default:
      description: |
        Response body for when the authentication fails with codes other than 401
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

  schemas:
    Authenticate:
      type: object
      properties:
        grant_type:
          type: string
          default: "client_credentials"
        client_id:
          type: string
          default: "b8f8f8f8-f8f8-f8f8-f8f8-f8f8f8f8f8f8"
        client_secret:
          type: string
          default: "b8f8f8f8-f8f8-f8f8-f8f8-f8f8f8f8f8f8"
        scope:
          type: string
          default: "https://api.businesscentral.dynamics.com/.default"

    AuthenticateResponse:
      type: object
      properties:
        token_type:
          type: string
        expires_in:
          type: integer
        ext_expires_in:
          type: integer
        access_token:
          type: string

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        error_description:
          type: string
        error_codes:
          type: array
          items:
            type: integer
        timestamp:
          type: string
        trace_id:
          type: string
        correlation_id:
          type: string
        error_uri:
          type: string
